### ISSUE TITLE
Support different persistence stores for different roots

### ISSUE THREAD

**Issue by larkin** [nasa/openmctweb#112]
It should be possible to have multiple root objects in MCT and for each root to persist objects to a different location.  Serverside access controls may exist per root object, but gracefully handling the application of those could be a follow-up issue.

Use cases:
* "My Items" root that is linked to currently active user's persistence store (where the server handles permissions).  Comes from JPL request.
* Per missions roots, where each mission has it's own root and stores files in a persistence store which has server-side access controls.  Comes from JPL request.
* Localstorage could be a separate root, allowing localstorage to be used as a sort of personal scratch pad for work.

**Comment by VWoeltjen** [comment]
Believe that #97 is a useful step toward this. Deciding on an appropriate persistence store based on location can be facilitated by tracking composition changes, which in turn is facilitated by consolidating these within the composition capability

**Comment by larkin** [comment]
@VWoeltjen Aaah, I knew there was something pending regarding this issue but wasn't sure which.  Thank you for linking this.

**Comment by VWoeltjen** [comment]
Believe this was resolved by #257. @larkin - please reopen if I'm missing something.

**Comment by larkin** [comment]
@VWoeltjen Yes, is completed.  Follow-ups exist for per-deployment changes to persistence.
