### ISSUE TITLE
[Time Conductor] Add domain selector

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#115]
Add a selector to choose among time domains to the time conductor. Can be limited to "UTC-like" time systems for now (don't need to support domains which can't be expressed as UTC yet)

**Comment by larkin** [comment]
@VWoeltjen: I recall discussing with you the idea of inspecting all telemetry metadata currently being represented and generating an inclusive set of all time domains available-- an "ideal" solution.  Unfortunately, that telemetry metadata is itself currently hardcoded, so there is little value in doing this right now.

In the context of this sprint, I think a reasonable solution would be to use a bundle constant to specify available domains, as that would have the same result as reading all telemetry metadata and would allow us to support the use case and improve it based on further discussions.  Later on, we could replace that bundle constant with an auto-generated list of domains without changing overall functionality.

**Comment by VWoeltjen** [comment]
Work in progress on two branches:

* open115 adds domain selector to time conductor from #104 
* open115b merges the above with changes in progress from #117, with some additional changes to position the domain selector

Believe these changes are ready for a pull request, holding off at least until #104 is merged
