### ISSUE TITLE
[Time Conductor] Refine markup/styling

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#117]
Refine markup/styling for the time conductor, added by #104

**Comment by VWoeltjen** [comment]
Specific things to look out for:

* Time label positioning in  platform/commonUI/general/res/templates/controls/time-controller.html
* General styling of platform/commonUI/general/res/templates/controls/datetime-picker.html
* Styling associated with adding the conductor to the view area in platform/features/conductor/src/ConductorRepresenter.js
  * In particular, this appears over (instead of below) certain views, like Layout

**Comment by charlesh88** [comment]
Actively starting on this now.

**Comment by charlesh88** [comment]
To-dos:
- Add back animation when values from dt picker are changed
- Show Victor non-dragging behavior when end is changed via dt picker in such a way that span is 0
