### ISSUE TITLE
[UI] Progress indicator for pending operations (e.g. duplicate)

### ISSUE THREAD

**Issue by larkin** [nasa/openmctweb#127]
The duplicate action can take a non-negligible amount of time to complete when duplicating large sets of objects.  However, the duplicate action appears to be complete immediately, though operations are still executing in the background.  I will file a separate ticket to prevent a user from seeing/interacting with the results of a duplicate operation before it is complete.

It seems that the duplicate action should have some kind of progress bar / completeness notifier that tells the user the duplicate has not yet finished.  Do we have designs for a sort of global progress bar or activity notifier for operations that may take some time?    

Follow-on: Should a pending action prevent the user from doing other things until it is completed?  (I'd say no, but they can't interact with the duplicated object until the action completes).

@charlesh88 sending your way for design considerations.

**Comment by larkin** [comment]
As @charlesh88 mentioned in #128, there is already design in the design docs for displaying notification messages similar to toasts.

A global progress bar w/ cancel action would be great-- need some place to show the action in progress á la
![action in progress with cancel](https://cloud.githubusercontent.com/assets/226503/9971607/042e1aa2-5e12-11e5-8ad5-02cef111dc52.png)

As mentioned in #128, the implementation could eventually evolve to show a placeholder object with progress indicators.  I don't think these are necessary for v1, but are great v2 candidates.

In the tree view, something like:
![tree view progress](https://cloud.githubusercontent.com/assets/226503/9971617/17cb6452-5e12-11e5-9853-043d992bb8a5.png)

In the items view: something like:
![screen shot 2015-09-18 at 2 33 19 pm](https://cloud.githubusercontent.com/assets/226503/9971646/48c51d78-5e12-11e5-88c3-181ff630f546.png)

**Comment by charlesh88** [comment]
Per discussion 9/21/15 CH, VW and PR: 
- v1: Modal blocking dialog with text messages and simple progress bar articulating process for the whole operation.
- v2: Block only during preparing to copy phase, then transition progress display to non-blocking indicator.

**Comment by charlesh88** [comment]
Fix styling in /platform/persistence/queue/res/templates/persistence-failure-dialog.html while you're at this.

**Comment by charlesh88** [comment]
Assigning to Andrew for implementation.

**Comment by akhenry** [comment]
Addressed by merged pull request https://github.com/nasa/openmctweb/pull/249

**Comment by RCarvalhoNASA** [comment]
Testathon 20151123:  Notification transitions to progress bar, though it is unclear to user why this transitions or what that means.  Progress bar seems to work fine.
