### ISSUE TITLE
[Edit] When editing an object found via search, Library does not load

### ISSUE THREAD

**Issue by larkin** [nasa/openmctweb#130]
1. Search for an object that supports editing & composition.
2. Select that object from the tree
3. Edit that object.
4. Note that Library shoes a loading spinner and never loads.

The expected behavior in this case is that the library pane would load and the object would support editing.

**Comment by larkin** [comment]
May be due to objects in search results not having location and thus not having context.

**Comment by VWoeltjen** [comment]
Marking resolved, can't reproduce; believe this was fixed by #119
