### ISSUE TITLE
show warning for unsupported browsers

### ISSUE THREAD

**Issue by larkin** [nasa/openmctweb#137]
Generally we say we are only compatible with Chrome.

There are a few browsers we almost support but don't fully support, and sometimes the bugs can be silent and undesirable.  We should show a notification to users when they are not using a browser we fully support.

**Comment by larkin** [comment]
Reported in https://github.jpl.nasa.gov/MissionControl/vista/issues/73

**Comment by fbender** [comment]
What's preventing you from supporting other evergreen browsers?

**Comment by larkin** [comment]
@fbender While we would love to support all evergreen browsers, we cannot currently ensure that OpenMCTWeb works in all evergreen browsers.  Minimizing our supported browsers allows us to focus our efforts elsewhere.

We will always welcome contributions that identify and/or fix compatibility issues.

**Comment by VWoeltjen** [comment]
@charlesh88 - are you fine with just throwing a warning notification at start up in this situation? I don't think it would need to be blocking.

Short text: "Unsupported browser"
Description: "This software has been developed and tested using the latest Google Chrome, and may be unstable in other browsers."

**Comment by akhenry** [comment]
Does this need any design done? We shouldn't use the notifications/dialogs framework for this in case a browser compatibility issue causes them to fail. It will need to be fairly minimalist. To be honest, it should probably have zero framework dependencies, on the basis that there is no guarantee that the framework has loaded at all.

**Comment by charlesh88** [comment]
Non-blocking notification is the right way to go. Should be the "Info" type, not an alert. The important thing here is that we remember the user has seen and acknowledged this and don't show again on this machine/in this session. If this is a good first candidate to implement the "Don't show me this again" checkbox in these kind of notifications, then by all means lets do that - this functionality isn't a high priority, but would be useful in general. 

In this a good "Help wanted" candidate?

**Comment by akhenry** [comment]
I think it's a perfect "help wanted" candidate.

**Comment by akhenry** [comment]
In fact, @fbender has separately expressed an interest in taking a look at this ticket, so I'll give him first dibs.

**Comment by fbender** [comment]
I will have a look at this and try to improve on it. The browser test is pretty minimal and may return quite some false positives (UserAgent is unreliable/highly complex for checking browser name, see [1] [2] [3] [4]).

[1] https://developer.mozilla.org/en-US/docs/Browser_detection_using_the_user_agent
[2] http://srfrnk.github.io/ng-device-detector/ (Angular browser detection module)
[3] https://github.com/darcyclarke/Detect.js (a good JS library)
[4] https://github.com/WhichBrowser/Parser#whichbrowserparser (a good PHP library)

**Comment by RCarvalhoNASA** [comment]
Testathon 20151207 this alert appears as expected Firefox in windows.  And having seen the problems in windows/firefox layout as it just comes up, I can also confirm that the browser is not currently supported.

**Comment by charlesh88** [comment]
Testathon 20151207: verified

**Comment by fbender** [comment]
Which layout issue are you seeing?

**Comment by akhenry** [comment]
@RCarvalhoNASA were you viewing a particular object, or was this just the "home screen" as it were? I see an issue with the navigation pane being collapsed in the home screen, is this what you saw?

**Comment by RCarvalhoNASA** [comment]
I'm not in a place on the network today where I can go to this, but what I recall is that on the 'home screen' all of the object icons started at the upper left of the browser window, and were basically obscuring the top bar, the tree, and everything else that should have been outside of their area.  I can try and get a screenshot tomorrow when I'm back in the lab.

**Comment by fbender** [comment]
OK if that is the issue, I saw that, too. You can drag the sidebar border to where you like, though, so this works theoretically. Probably just needs some fixing in the calculation logic. Will look into that.

**Comment by RCarvalhoNASA** [comment]
![chrome](https://cloud.githubusercontent.com/assets/5769437/11728613/aad3d8b0-9f3f-11e5-9566-addd1591e095.JPG)
![firefox](https://cloud.githubusercontent.com/assets/5769437/11728614/aad34008-9f3f-11e5-9da5-43afdaa9fb78.JPG)
Attached are some screenshots to show the difference between the Chrome and Firefox 'home' views.
