### ISSUE TITLE
Info bubbles can block mouse clicks

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#14]
Info bubble (which shows on hover over objects in a tree) appears to block mouse clicks when attempting to navigate to these objects.

To reproduce:
- Hover over a domain object's label in the tree on the left hand side
- Left click
- Observe: Domain object does not get navigated-to
- Expected behavior: Domain object gets highlighted, view appears to the right hand side

**Comment by VWoeltjen** [comment]
Believe this could be addressed by adding an X offset in InfoConstants in platform/commonUI/inspect

**Comment by charlesh88** [comment]
Actually, I think the better course is to apply CSS style "pointer-events: none" to the hover bubbles. I will take care of this.

**Comment by charlesh88** [comment]
Pushed to origin open12
- Added CSS class "bubble-container" to BUBBLE_TEMPLATE;
- bubble-container utilizes CSS "pointer-events: none";
- Changed INFO_HOVER_DELAY constant from 500ms to 2000ms;

**Comment by charlesh88** [comment]
Author checklist:
- Changes address original issue? - *Y*
- Unit tests included and/or updated with changes? - *N/A, no new code*
- Command line build passes?  - *No Maven installed*
- Expect to pass code review? - *Y*
- Project-specific information isolated to appropriate branches? - *Y*

**Comment by charlesh88** [comment]
Code pushed to github open14.
