### ISSUE TITLE
[Time Conductor] Fixed position updates need to be throttled

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#156]
Create a fixed position display with some telemetry elements, and scrub the time controller about wildly.

Observe: Updates to the displayed fixed position telemetry lag behind, the updates continue to display for a short time after the gesture is completed.

**Comment by larkin** [comment]
Another option that also prevents hammering the backend with repeat queries is to only refresh the display when the drag action ends. Thoughts?

On Sep 28, 2015, at 3:55 PM, Victor Woeltjen <notifications@github.com<mailto:notifications@github.com>> wrote:


Create a fixed position display with some telemetry elements, and scrub the time controller about wildly.

Observe: Updates to the displayed fixed position telemetry lag behind, the updates continue to display for a short time after the gesture is completed.

**Comment by charlesh88** [comment]
If we have to go this way, I like Pete's idea, but whatever is in view should visually articulate that it's going to be affected by the time slider being changed. Ideal scenario would be to put a wait spinner (or something similar) over the display - not replace it - while the user is dragging. Once the drag stops, the object can be replaced with a "real" wait spinner.

**Comment by larkin** [comment]
That would be reasonable to support and pretty clean: The time conductor is injected in a way that has knowledge of the other representation (e.g. a layout/plot/etc), and the time conductor could apply a class on the container for that representation, and that class could add a transparent overlay (via :before) to be placed over the entire representation.

Then, it's just a matter of toggling that class on when the user is interacting with the time slider (e.g. dragging/scrubbing) and toggling it off when the user has completed dragging/scrubbing.

And then, the "real" wait spinners would be those implemented by the specific views in response to a requery.

**Comment by VWoeltjen** [comment]
How worried are we about repeat backend requests? The `throttle` approach would be a smaller change, and if we used a reasonable duration (250ms, 500ms...) we'd be hammering with a lot fewer requests than, say, generic search (although those requests are just plain retrievals - no work for the server to filter by start/end times.) As a benefit, you'd still get to see Fixed Position updates in near-real-time in direct response to the movement of the slider.

**Comment by larkin** [comment]
Fixed position updates would still be lad requeries, right?  That's still a query to server.

Aside from the "cool factor", I don't see a lot of value in real-time fixed position updates in response to scrubbing.  There are better tools for locating a specific value in a series of values-- e.g. plot, data table.

Waiting for the user interaction to end before kicking off an update is generally preferred over causing a lot of unnecessary recalculation to occur while sliding.  Directly impacts mobile performance, too.

**Comment by VWoeltjen** [comment]
I don't want to hastily brush this off as "cool factor" - if you're trying to slide back to a specific feature in a plot, for instance, having to wait until mouseup to see that feature (or not) gets a little tedious. 

This clearly needs to be throttled, at least, but I don't see a reason to presume that a more complex solution is necessary, particularly if it loses functionality.

**Comment by larkin** [comment]
If you're trying to slide back to a specific feature in the plot, I imagine you'd just interact directly with the plot to do so.  Don't see fixed position being a good tool for time range selection.

**Comment by larkin** [comment]
Apologies, this would really belong in the time conductor pull request, I will get that review started soon.

In terms of complexity, there is a singular event already associated with the end of the user interaction (say mouseup or touchup, or the more abstract dragEnd), and attaching a handler to that event as opposed to the current getter+setter+watcher spaghetti may help simplify the flow of logic inside of the controller.

**Comment by VWoeltjen** [comment]
Believe this will be addressed by changes made in the context of #104

**Comment by VWoeltjen** [comment]
Addressed in changes resulting from review of #104
