### ISSUE TITLE
[Mobile] Suppress Create button in Mobile

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#157]
Only show the Create button on desktop devices; not supporting composition on mobile devices.

**Comment by larkin** [comment]
I would love to see this as a bundle configuration option so we have flexibility.

**Comment by VWoeltjen** [comment]
Probably don't like the solution from the linked pull request; we want to have this button in development environments (to test on actual mobile devices with browser local storage).

Want to solve this with bundles with custom stylesheets to enable/disable this instead.

(Suggestion: Disable this with CSS on mobile normally, and add a `example/mobile` bundle with stylesheets that un-suppresses this, so that by default Create is missing, which will be more useful for general deployments. Developers can add that bundle to support mobile testing as-needed.)

**Comment by charlesh88** [comment]
Working on this.

**Comment by charlesh88** [comment]
In-progress work pushed to open157a (based on open157).

**Comment by charlesh88** [comment]
The solution here should use flex layout; pending completion of #195 to allow this.

**Comment by charlesh88** [comment]
Hide Create button by default in mobile, but allow dev users to re-display it by including a bundle. Work to be pushed to branch open250. Usage: add "example/mobile" to bundles.json.
