### ISSUE TITLE
[UX] Process and event messaging

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmctweb#159]
When a user or the system initiates an action, such as saving changes to a thing, that operation may take some time. The user should be made aware via a non-obtrusive message indicator in the status bar - like "Saving..." with a progress bar. Tree items involved should also display a visual state, such as an animated watch icon.
If the action fails, the reasons for this can be many. We should display a message in the status bar with a button to see the details, or a Try Again action. Details could be visible in an overlay dialog. Tree items should also articulate this state.
Do some design for this in advance of Idea Week. This is related to 
- #58 Persistence didn't work, with #154 UI design task
- #127, #128 Modal dialog to prevent interaction while duplicating. See important notes about interaction phases in #128.

**Comment by charlesh88** [comment]
Work in progress, would like to review with team.

**Comment by charlesh88** [comment]
Review, 9/30/15 Victor, Pete, Andrew
1. Missed category: progress can be shown, but can't quantify when it'll be done. Allow status bar to be either barber pole, or percent-based progress. Show as examples.
2. Remove "X" from progress dialog, show more verbose button label example.
3. "Dismiss" in message queue removes that item from the queue. Some messages will not be able to be dismissed.
4. Add an example that shows a modal blocker with actions like "Try Again" or "Dismiss".
5. Remove manual minimize in banners; replace with "Dismiss" or other key action like "Try Again". Banners can't be manually minimized, or perhaps can be via a more subtle control.
6. Remove "More..." from dialog in page 13.

**Comment by charlesh88** [comment]
UI doc updated at https://drive.google.com/a/nasa.gov/file/d/0B0v27OM1JkSeR001RFJZMk43QVk/view?usp=sharing

**Comment by akhenry** [comment]
I think it's looking really great. A couple of comments
- I do wonder if perhaps the in progress banners should be a different color. Orange is being used elsewhere to indicate a warning condition (telemetry values reaching some high or low threshold, but in this case it's a nominal condition. Perhaps gray or blue could be used instead?
- Maybe we should have distinct icons for dismiss and minimize in the banner clarify that the result of clicking it will be different depending on whether it's a success message or a progress / error message.

**Comment by charlesh88** [comment]
Good stuff, thanks.
- Don't read too much into colors in this document: it's really not intended as a design mockup, although some of that leaks in. I'm **very** cognizant of color and its usage, particularly in limits. Orange actually isn't being used for limits; we use red and yellow. I'm actually using orange elsewhere to articulate a "paused" state, when an object or display that was displaying streaming real-time data is no longer doing so, such as when a user zooms into an image. Final colors for these banners will be worked out by me during the CSS phase with input from users like Mark Shirley and Sarah.
- The success banners don't minimize, they just go away. My intent for dismissing the in-progress and alert banners is that they will animate to the left and fade out. If the minimized message icon (now a bell) wasn't there, it would appear. I'm not sure I want to use a different icon than the "x" in the banner for the different cases - that increases the cognitive load for something that the user just uses to "make this thing go away". If we determine later that a different icon is needed, it will be trivial to change that.

**Comment by VWoeltjen** [comment]
That's a really good callout in terms of progress indicator color, we've gotten similar feedback from users. I think there are some cases where it would be appropriate to treat a progress indicator as warning-like (maybe even error-like?); for instance, in cases where the state of the system is somehow inconsistent until the operation is completed.

My inclination here would be, in the API, to separate out severity from notification type. So one could, in principle, have a warning-level progress indicator or an informational-level progress indicator. Stick one class on to reflect severity, another to reflect type, and then all the fine-tuning of the appearance of these can just be handled with CSS as Charles suggests. Whether or not we ever really use severity level for progress indicators, I think this still simplifies the problem enough to be worthwhile.

**Comment by charlesh88** [comment]
I was thinking exactly the same thing about separating severity from notification type.
