### ISSUE TITLE
Open in New Tab

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#16]
Add an Open in New Tab action; this should be available in two places:

- From the context menu for a domain object
- From the top-right set of buttons in Browse mode

There's a placeholder for this action in platform/commonUI/browse/src/windowing/NewWindowAction.js with some metadata in platform/commonUI/browse/bundle.json (note that the name will need to change from Open in New Window to Open in New Tab)

There are also some CSS changes which are suppressing the presence of this button currently; check with Charles about undoing these changes.

This will depend on addressability (see #8) on branch open1149, so should start from that branch if it hasn't been merged to master yet

**Comment by charlesh88** [comment]
Is there a branch yet for this? I don't see it. I'd like to enable the new window button so Shivam can work on this.

**Comment by VWoeltjen** [comment]
There is not, you can go ahead and create one. Start from 1149

**Comment by charlesh88** [comment]
That's my confusion: there is no origin/open1149 that I see on git.

**Comment by VWoeltjen** [comment]
Ah, got it - this was on github but not the private git instance. It is now on both

**Comment by slhale** [comment]
We have some questions about addressability with respect to this issue. Both Shivam and I can get addressability to work on our setups, but neither of use can copy-paste those URLs into new tabs/windows and have it stay on the correct page. We thought this might have to do with having a server set up, but Shivam set up a server on his computer, which did not make a difference. Is there something additional necessary to get this to work? Does it have to do with the bundles we are using?

**Comment by VWoeltjen** [comment]
Good question; in our default configuration we're using example persistence, which (in spite of the name) does not actually persist anything.

Steps to set up an environment with actual persistence:
- Download/install ElasticSearch (https://www.elastic.co/)
- Enable cross-origin resource sharing in ElasticSearch (necessary because the client will be running from a different host/port)
  - Add `http.cors.enabled: true` to `config/elasticsearch.yml` in your ElasticSearch installation
  - Also a good idea to add `network.host: localhost` in the same file to only accept connections from your own machine
- In bundles.json, remove `"example/persistence"` and add `"platform/persistence/elastic"` to utilize the ElasticSearch adapter
- Additionally, configure platform/persistence/elastic to look at your instance of ElasticSearch
  - In `platform/persistence/elastic/bundle.json`, change constant `ELASTIC_ROOT` from `/elastic` to `http://localhost:9200`
- Run ElasticSearch, then run the client; you should now be able to create domain objects and have them persist (e.g. still be present after reloading), which in turn should allow you to cut & paste URLs (and open in new tab...)

**Comment by VWoeltjen** [comment]
Shivam will be working on this issue
