### ISSUE TITLE
Progress Dialog View

### ISSUE THREAD

**Issue by larkin** [nasa/openmctweb#163]
Charles has been prototyping a progress dialog box for blocking operations in #127.  It seems that this could be implemented as a representation with a relatively standardized data model, and with two way binding, becomes very easy to implement.

example invocation: `overlayService.createOverlay('progress', progressModel);` where progress model supports configuration options such as:

 * `name` - "Duplication in progress...", shown as large header.
 * `status` - "Preparing to Copy", show above progress bar.  Can be updated by underlying code as needed.
 * `unknownDuration` - boolean, if true, show wait spinner.
 * `progressAmount` - integer, represents progress out of 100.  if undefined, don't show progress bar.
 * `progressText` - text description of progress, e.g. "Time remaining: 2 minutes"
 * `actions` - an array of objects, corresponding to buttons on the dialog.  Each action definition is an object with a label and a function for invoking that action.  e.g. `{label: "cancel", action: function () {cancelSomthing();}}`

When implemented, will support #128.

**Comment by akhenry** [comment]
The changes for this issue have been committed along with #155 and #170 in branch [Open155](https://github.com/nasa/openmctweb/tree/open155). See associated [Pull Request](https://github.com/nasa/openmctweb/pull/186)

**Comment by akhenry** [comment]
This is closed by merge of pull request https://github.com/nasa/openmctweb/pull/186
