### ISSUE TITLE
Add loading screen before framework initialization

### ISSUE THREAD

**Issue by larkin** [nasa/openmctweb#164]
Request from JPL:

Fresh loads of the application can take 3-10 seconds before any thing is visible on the webpage, which gives the impression that nothing is loading.

We should include some kind of loading indicator in index.html so that people know the application is loading and will feel safer.

**Comment by larkin** [comment]
A certain configuration change in one of our deployments has pushed the loading time up to ~30 seconds-- a rather long time to stare at a white screen.

**Comment by VWoeltjen** [comment]
@charlesh88 - thinking this is a change you could do directly in index.html, correct?

**Comment by charlesh88** [comment]
It would be nice to show a branded title screen. Must be done in index.html, with no CSS loaded via Angular. Talk to Pete and Victor further about what's possible and how this works.

**Comment by charlesh88** [comment]
@VWoeltjen @larkin Big question here is when will the app know which application it is (WARP, VISTA, OMCTW, etc.)? My guess at the answer is "too late to show a branded title screen" and that we need a completely generic "Application is initializing" screen instead. Can you guys confirm?

**Comment by larkin** [comment]
Each app has a different index.html file; I think it's safe to use a branded screen.

**Comment by VWoeltjen** [comment]
> Each app has a different index.html file; I think it's safe to use a branded screen.

:+1:

**Comment by charlesh88** [comment]
Can start on this now - note that index.html may have merge conflicts in the short term, but that's Ok.

**Comment by charlesh88** [comment]
Starting work on this in branch open164.

**Comment by charlesh88** [comment]
* Applied to vista with https://github.jpl.nasa.gov/MissionControl/vista/issues/299
* Applied to warp with https://developer.nasa.gov/mct/warp/issues/139

**Comment by charlesh88** [comment]
PRs filed: 
* Open MCT: https://github.com/nasa/openmctweb/pull/702
* VISTA: https://github.jpl.nasa.gov/MissionControl/vista/pull/300
* WARP: https://developer.nasa.gov/mct/warp/pull/140

**Comment by charlesh88** [comment]
Merged into master; closing.
