### ISSUE TITLE
[Mobile] Smaller-screen laptop treated as mobile device

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#169]
Laptops with small screens can display Open MCT Web incorrectly due to CSS rules which detect small screens as mobile devices.

Known cases where this occurs:

* The little arrow has gone missing from info bubbles
  * A little bit of git bisect points to this commit from mobile: 9b922913a06addda902ad44f8c54e7d0ffe5ae7d
* Buttons to collapse left/right panes do not display (see #240)

**Comment by VWoeltjen** [comment]
Looks like this was [at least somewhat intentional](https://github.com/nasa/openmctweb/blob/9b922913a06addda902ad44f8c54e7d0ffe5ae7d/platform/commonUI/general/res/sass/helpers/_bubbles.scss#L82-L88)

I was a little confused when I saw this because I'd been working on info service yesterday and was seeing arrows at that point. My guess is that now that I'm viewing this on my 11-in laptop monitor instead of a larger monitor, my device type is being detected differently and those arrows are being omitted.

Reassigning to @charlesh88 since this appears that it will be a CSS change

**Comment by VWoeltjen** [comment]
Resolution is 1366x768

**Comment by charlesh88** [comment]
Further discussion ensued regarding the close "x" icon not being displayed for the treeview on Victor's 1366 x 768 screen. 
![missingx](https://cloud.githubusercontent.com/assets/1685764/10948723/e9f8e238-82e3-11e5-915c-5a5f62a8f9e5.png)

From Victor in #240:
> Verified that this is indeed triggered by my little screen size; as a test, found-replaced min-device-height: 800 with min-device-height: 600 locally in theme-espresso.css and those little X's show up and behave as expected.

**Comment by larkin** [comment]
I think the common solution is to ignore device height in setting breakpoints and only using device width for queries.

**Comment by charlesh88** [comment]
Beginning work on this in open169, based on master.

**Comment by charlesh88** [comment]
Completed work pushed to open169 and filed pull request #321.

**Comment by larkin** [comment]
Realized I said "device width" earlier, but I was thinking "max-width" may be better than "max-device-width" because "max-device-width" doesn't take into account portrait vs landscape.
* max-width is the width of the target display area, e.g. the browser
* max-device-width is the width of the device's entire rendering area, i.e. the actual device screen

**Comment by charlesh88** [comment]
Retina screen is a problem, talk to Andrew.

**Comment by charlesh88** [comment]
Actively looking at this now.

**Comment by charlesh88** [comment]
Problem is the breakpoints. open169a da8fb99e82671b6f0d5bd367b5c112a3e3db84e5 changes desktop to enable at 1280 max-device-width; tablet is 768 x 1024.

**Comment by charlesh88** [comment]
Pull request filed with #358 for short-term solution. Leaving this open for a better long-term solution.

**Comment by charlesh88** [comment]
Mix #436 into the mix here too.

**Comment by charlesh88** [comment]
After discussion at our tag-up, we need to allow index.html to call agentService (or another function) to accomplish something like this:
`<body class="user-environ" ng-class="{ 'desktop': agentService.isMobile() === false,'mobile': agentService.isMobile() === true }" ng-view>`

The problem of course is that the service needs to be loaded before index.html calls it. Reassigning to Victor for implementation.

**Comment by charlesh88** [comment]
Filed PR with #691, closing.
