### ISSUE TITLE
[Frontend] Markup and styling for event messaging

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmctweb#170]
Provide static markup and CSS styling for message banners and minimized icon indicators. Based on designs in https://drive.google.com/open?id=0B0v27OM1JkSeR001RFJZMk43QVk. New dialog elements to be covered in a separate issue. 
Related to #159.
@akhenry @VWoeltjen

**Comment by charlesh88** [comment]
@akhenry Progress bar and dialogs now looking good. Tomorrow, will stub in multiple messages in scrolling overlay list.

**Comment by charlesh88** [comment]
@akhenry Just pushed my work on the messages as singleton and in the messages list. You can invoke the dialogs by going to the status bar and hovering over the green box+arrow icon. 

This is as functionally solid as I intend to make it right now - hopefully I haven't done anything bad. I will be continuing on styling, particularly checking mobile. Don't intend to touch any JS, and don't anticipate touching markup (particularly messages.html), hopefully it's a just a little more CSS sanding.

**Comment by charlesh88** [comment]
@akhenry Just pushed final work on messages. Added a Cancel function and button to DialogService for the new message list prototype, so I lied about not touching any JS :) That's it for now: all dialogs should be looking good in all themes and both desktop and mobile.
Tomorrow Friday: I'm finally going to try to get to some Idea week stuff, but ping me on cell at 415 342-8942 if you have any questions.

**Comment by akhenry** [comment]
@charlesh88 Awesome stuff, thanks Charles! I'll try and integrate everything tomorrow.

**Comment by akhenry** [comment]
I have a quick question regarding the severity levels in messages. I have only been working with ‘success’ and ‘error’ thus far. I notice in your code you’re referencing info, alert, and error.

- Is alert a ‘warning’, somewhere between info (neutral/positive), and error (bad)?
- Is ‘info' neutral, or positive? This probably sounds like an unnecessarily academic exploration of semantics, but the reason I ask is to make sure that I use the right severity level for success messages :).  So presumably a message indicating success would be ‘info’?

For now I’m going to use Info for ‘success’ messages, and we can have a discussion about whether it’s even useful to distinguish between neutral and positive messages.

**Comment by VWoeltjen** [comment]
A convention I'm used to seeing is three messaging levels (info, warning, error); Java Swing, for example, has built-in support for dialogs of these types. These are analogous to logging message levels (except there's no "debug" level.) The convention we've been using for logging messages is:

* :information_source: _Informational_: Records an event within the system that is nominal but noteworthy.
* :warning: _Warning_: Records an event within the system that is off-nominal but recoverable.
* :x: _Error_: Records an event within the system that is off-nominal and non-recoverable.

I think these definitions map reasonably well to user-facing messaging, with the distinction that "system" in the case of logging is specifically the software (Open MCT Web + plugins), but in the case of user messaging may be somewhat broader (depends on what the user perceives as "the system" they're interacting with.)  Recoverability is also different here - I think I'd draw the line here as meaning recoverable _by the system_. So you'd show a warning for off-nominal situations that the system believes it has handled or will handle, and error messages for situations where some user action is required to correct the situation (even if that user action is "pick from these three options to recover").

By these definitions, I'd treat success as "informational". I'm guessing "alert" could follow the definition of "warning" above.

All of the above is just opinion/advice, which should be superseded by actual UX guidance from @charlesh88

**Comment by larkin** [comment]
ymmv

http://bikeshed.com/

**Comment by akhenry** [comment]
Three levels works for me, let's stick with that.

**Comment by charlesh88** [comment]
I like and agree with Victor's breakdown above. Let's keep it simple now and add more complexity if/when needed.

That said, I want to talk for a sec about informational vs. success messages: I feel strongly that we need to be able to communicate successful results in a style that communicates "success" (green-ish color, icon, etc.). If all informational messages are success messages than we're good with a single level of informational message. If we need to have an informational message that is not a success message, but also isn't a warning or an error, then we should introduce an additional level. 

I may take a bit of time and matrix out some example events and the resulting UX as I see it to create some straw men to poke at.

**Comment by charlesh88** [comment]
Well, my in-progress matrix just paid off: came up with an example of an informational non-success message that is also not *really* a warning and certainly not an error: user initiates an action like duping a large number of items that may or may not result in an initial blocking dialog but definitely results in an asynchronous "Duplication in progress" message banner. This may be able to be framed as a "warning", but I think that will depend on what other kinds of things we're warning users about.
