### ISSUE TITLE
Time Conductor needs styles for snow theme

### ISSUE THREAD

**Issue by larkin** [nasa/openmctweb#178]
The Time Conductor is very hard to use in the snow theme, @charlesh88 does it need style changes?

![screen shot 2015-10-09 at 10 03 53 am](https://cloud.githubusercontent.com/assets/226503/10400381/2b4edf3e-6e6d-11e5-9361-59d8fe6d05a8.png)

**Comment by larkin** [comment]
This may just be me not using the latest master, hold on...

**Comment by charlesh88** [comment]
That is way out of date; TC is fully Snow-styled and should work very nicely.

**Comment by larkin** [comment]
Yeah there was a bit of confusion with the styling pull request (#162) getting merged into open1515 after open1515 had been merged to master, so the changes hadn't actually be merged to master.  Victor is merging it to master now.

**Comment by VWoeltjen** [comment]
Merged the aforementioned changes into master. Time Conductor in Snow now appears as:

![tc-snow](https://cloud.githubusercontent.com/assets/1685764/10400754/848e2dfa-6e6f-11e5-9adf-e3b7065d4d9a.png)

Pretty like a unicorn.

**Comment by larkin** [comment]
🎠
