### ISSUE TITLE
[Events] Implement event message generator and view

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmctweb#18]
Implement a new example generator that synthesizes representative event messages.

**Comment by charlesh88** [comment]
Initial version of generator and stubbed in Event Message view pushed to open18.

**Comment by charlesh88** [comment]
Shivam, it's all yours - thanks.

**Comment by VWoeltjen** [comment]
Sarah will be working on this issue

**Comment by charlesh88** [comment]
From Mark via JIRA:
I've attached a sample of what events look like in itos. The columns are:
1. Severity level (one of TRACE, DEBUG, INFO, WARN, ERROR, FATAL)
2. ITOS component doing the logging
3. ITOS timestamp
4. Formatted event message (for fsw events, the fields within this message are)
4a. s/c timestamp
4b. FSW component generating the message
4c. event id
4d. severity level
4e. message

There is some info that's not present in the text of the message itself but as other fields within an event packet. That info should be presented to the user. Either the client should take several fields and combine them into a string to present to the user or the server should. But for RP15, we can get away with just showing the text field and the timestamp, I think.

**Comment by VWoeltjen** [comment]
Merged with #22
