### ISSUE TITLE
[Time Conductor] Adjust markup/styling for domain selector

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#180]
This applies to changes pending integration, #179 

Added a `time-conductor` template in the context of that pull request which adds on a domain selector, positioned using some in-line styling; see `platform/features/conductor/res/templates/time-conductor.html`

Would like to hoist these out into CSS properly. Also, some of the specifics of the appearance of the select box could use refinement (e.g. font seems a little too large, probably just some class that needs to be added)

**Comment by VWoeltjen** [comment]
Assuming these changes will be fairly small, it will probably be simplest to wait until #179 has been merged.

**Comment by charlesh88** [comment]
@VWoeltjen @larkin Going to knock this out this morning.

**Comment by charlesh88** [comment]
Review and integrate created with #183. Will resolve this when open180 is merged into master.
