### ISSUE TITLE
DateSelector should support typing in a date

### ISSUE THREAD

**Issue by larkin** [nasa/openmctweb#181]
The DateSelector currently only allows dates to be selected via the widget.  I'm finding this rather cumbersome in the TimeConductor when trying to select specific time periods in the past.  As I know the precise date, I'd like to be able to directly enter it.

For instance, if I wanted to select "2015-210", I should be able to type "2015-210" and have it understand that day.  If I don't specify an hour or month or day, it's safe to assume that I'm looking for 2015-210 00:00:00.000.

**Comment by VWoeltjen** [comment]
This is a highly-desirable next step toward implementing time controller

This is already captured in designs for time conductor, should consult those

**Comment by VWoeltjen** [comment]
Thinking here is to implement a single text field per date for now (instead of split across dashes as in the UI guide); splitting across dashes will be hard to support from #181, so want to follow a simple validate/parse/format model for now.

**Comment by larkin** [comment]
I like single field, can iterate on how to improve selection for different date formats later on.

Somewhere under the covers, what do you think about a type registry that has no bundle dependencies (aside from moment) and supports methods like:

* `dateFormat.SOL.toNumber(stringValue)` -> `numberValue`
* `dateFormat.SOL.toString(numberValue)` -> `stringValue`
* `dateFormat.SCET.toNumber(stringValue)` -> `numberValue`
* etc.

The idea being it would be independent and reusable in different areas of code, and then be connected to different components (telemetry providers, views, dateselector) by minimal glue.

**Comment by VWoeltjen** [comment]
Think that makes sense, more or less along the lines of what I was thinking. I might handle that as a composite service to make it simple to extend in different variants:

DateService |
-----------------|
parse(value : string, key? : string) : number |
format(value : number, key? : string) : string |
validate(value : string, key? : string) : boolean |

...defaulting to UTC time stamps if `key` is unspecified.

**Comment by larkin** [comment]
:+1:

**Comment by VWoeltjen** [comment]
Should be filing a PR shortly

@charlesh88  - Should I file a follow up for markup/styling? This is looking like:

![tc-err](https://cloud.githubusercontent.com/assets/1685764/10652090/6578d0bc-7808-11e5-9407-d01a3e0aeecf.png)

**Comment by VWoeltjen** [comment]
Addressed by #202
