### ISSUE TITLE
DateSelector should support configurable time formats

### ISSUE THREAD

**Issue by larkin** [nasa/openmctweb#182]
When using the domain selector with the time conductor, each domain may have a different format.  For example, SCET is `YYYY-DDD-HH:mm:ss.sss` and SOL (or LST/MET) is `<some-prefix>-DDD-HH:mm:ss.sss`.

The date selector should expose arguments for controlling the input format of the date so that the time conductor can display dates in the correct format for the selected domain.  Text entry of dates (when added by #181) should be parsed using the format specified.

If a format is not specified, the date selector should fall back to a reasonable default.

**Comment by VWoeltjen** [comment]
Along with #181, this is a highly-desirable next step for time controller (and telemetry visualization generally)

**Comment by VWoeltjen** [comment]
Branching open182 from open181

**Comment by VWoeltjen** [comment]
Running into a bit of oddness when switching between UTC-like domains to non-UTC-like domains. The trickiness is that there isn't necessarily a mapping (even in principle) between non-UTC-like domains and UTC times (certain counters, for instance, behave like this.)

Thinking that `DateService` (as described in comments to #181) could use some additional methods to support this:

* Getting a "now"-like value for that time range. For things like sols elapsed on Mars, we can do something reasonable based on available data for a given mission.
* Getting a reasonable default time span for the time controller, or just some meaningful day-like increment.

**Comment by larkin** [comment]
I think a "default time span" is out of scope for the date service, but I do like the concept of "now" being implemented differently for each domain-- especially those that define their own epoch.

The time conductor can subtract a constant (say, 24hrs) to find the initial time window, and that holds up well for all current domains.  If it's not good enough later, we can change it.

**Comment by VWoeltjen** [comment]
The way I've approached this in #204 is to publish meaningful increments on a per-time-system basis. I'm open to other solutions, but it's not quite as out-of-scope for that component as a `getDefaultTimeConductorBounds` would be.

The immediate use case is to allow a 1-sol default duration for LST. I guess we can call 24 hours close enough (at the risk of alienating Martian users) but I'd only want to do that if we really wanted more time to consider our approach for doing so.

**Comment by larkin** [comment]
@VWoeltjen Funny about those martians, for our definition of LST, a sol is considered to be 24 hours (not 24 hours and 37 minutes or whatever).  They're just `longer` seconds than our seconds on earth.  Trying to properly represent it breaks many packages and really complicates things.

**Comment by VWoeltjen** [comment]
Interesting! I guess treating all domain values is still safe at that point (although that won't always be the case) so I suppose we can defer dealing with that default bounds problem for now
