### ISSUE TITLE
Tree does not properly display when search bundle is excluded

### ISSUE THREAD

**Issue by larkin** [nasa/openmctweb#185]
When the search bundle is not included, there is a blank space above the tree view where the search bar would display, and a warning "No representation found for search" is logged in the console.

The tree looks like:
![screen shot 2015-10-14 at 11 39 55 am](https://cloud.githubusercontent.com/assets/226503/10493889/5354dce6-7268-11e5-97cc-e3df45e29874.png)

Expected functionality would be that when the search bundle is excluded, there would be no blank space above the Tree view, and no warning would be logged.

**Comment by charlesh88** [comment]
@larkin Is this an issue for JPL, are they not using search?

**Comment by larkin** [comment]
@charlesh88 they are currently using it, so not a problem in production.  We'd discussed not including it in the next warp build due to performance concerns, though those concerns should be resolved by fixes before the next warp build goes live.

I'm happy to say this is a won't fix, as we expect search to be enabled in most environments.

**Comment by charlesh88** [comment]
The solution here should use flex layout; pending completion of #195 to allow this.

**Comment by charlesh88** [comment]
#250 implements the left "tree" pane area using CSS flexbox layout, allowing elements to be loaded (via inclusion/exclusion of bundles) and the display cleanly adapting to the presence or absence of elements.
