### ISSUE TITLE
mct-resize triggers excessive digest cycles

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#19]
The `mct-resize` directive (defined in platform/commonUI/general) monitors the size of an element by polling on a `$timeout`, which in turn will trigger a new digest cycle as it is called currently (an extra parameter can be provided to suppress this)

Instead, it would be preferable to fire a digest cycle only when an element's size actually changes; there is already a check for this change, so adding the extra argument to `$timeout` and invoking `scope.$apply` should achieve the desired result (the existing `scope.$eval` may be enough that the `$apply` call is not needed at all, if `$eval` triggers a digest - not sure on this)

**Comment by peter-sa** [comment]
I've been looking for "help wanted" tasks to begin working on as an open-source contributor, but this appears to me to already be complete.  Am I missing anything?

**Comment by akhenry** [comment]
Agreed, from the PR it looks like this has been done. @VWoeltjen can we close this?

**Comment by VWoeltjen** [comment]
Yes, closing now.
