### ISSUE TITLE
[Representation] Remove mct-representation/mct-include elements when key not found

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#195]
When attempting to use either an `mct-representation` or `mct-include` for which a matching key does not exist, remove the element from the DOM instead of simply leaving it empty. (Additionally, this means adding it back to the DOM if at some future point the representation/include becomes valid; see `ng-if`)

@charlesh88 has requested this feature as it simplifies the use of Flex layouts in templates where some part of the template needs to be presented differently depending on whether or not some other template/representation is present.

**Comment by VWoeltjen** [comment]
Wanted to solve this with element-level transclusion (adding elements to the DOM only if/when a representation is available) but only one `transclude: 'element'` directive is allowed per HTML element. This conflicts with any `mct-device`, `ng-if`, `ng-repeat` directives attached to an element. 

Will explore simulating the behavior of `transclude: 'element'` by explicitly swapping out elements with some placeholder (e.g. a comment, as Angular does); this will probably not be much more complicated than using `transclude` anyway.

**Comment by charlesh88** [comment]
So, if an <mct-rep>'s key can't be found, it'll be completely replaced with a comment, yes? If so, sounds good.

**Comment by VWoeltjen** [comment]
That is correct, for both `mct-include` and `mct-representation`. 

Additionally, `mct-representation` will be replaced with a comment when no domain object is available to represent (e.g. `<mct-representation key="'tree'" mct-object=undefined>` would be replaced with a comment.)
