### ISSUE TITLE
[New Edit Mode Prototype] Stub in markup for new Edit Mode

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmctweb#198]
Add markup elements/CSS and transitions to browse-object.html:
- Save/Cancel buttons
- Toolbar holder
- Outer wrapper

**Comment by charlesh88** [comment]
@akhenry @larkin I'm using [New Edit Mode Prototype] to prefix these tasks, suggest you do the same

**Comment by charlesh88** [comment]
@akhenry Andrew, this is ready for you to pick up. I've left in my placeholder HTML so you can see what it's supposed to look like once we wire up the representations. You should merge this into your own branch, or branch off this one, in case I need to update this branch.

**Comment by akhenry** [comment]
Thanks Charles,

I've merged your changes and pushed to branch "open199". I have enabled edit mode on drop for layouts so far, so feel free to check that out. NOTE: At the moment any compositional changes to a layout are persisted immediately. My next job is to prevent that from happening. I have a vague idea what's going on, so I should be able to fix it.

Andrew

**Comment by charlesh88** [comment]
@akhenry Wanted to mention: New Edit Mode needs to be initiated by both the drop AND a click of the Edit (pencil icon) button in the upper right of editable objects. Note that in some cases, clicking that Edit button actually takes the user to Edit Properties, for objects that don't really have editable contents, like a Sine Wave Generator.

**Comment by akhenry** [comment]
Edit button now works for enabling edit mode, as well as drag and drop. @charlesh88 in master, clicking the edit button of sine generators doesn't give me the edit properties dialog? Instead it shows me the "edit" screen with just the plot in it. Unless I'm missing something?

**Comment by akhenry** [comment]
Caveats: There is no way to save editing at the moment, and no onunload warning either.

**Comment by charlesh88** [comment]
Closing; initial markup and CSS was stubbed in. New markup or CSS needs for NEM should be filed as new issue, or within existing issues and assigned to Charles.
