### ISSUE TITLE
[New Edit Mode Prototype] Mode switching in views to allow drag and drop initiation of edit mode

### ISSUE THREAD

**Issue by akhenry** [nasa/openmctweb#199]
One proposal for new edit mode is to allow a user to edit a view seamlessly by dragging an object from the tree into a view. In a plot view, this would add the object as a second plot. In a layout view, this would add the object to the layout. Currently editing and browsing are two different views. This means that switching to edit mode cannot be performed seamlessly because a page load is necessary.

Editing elements should be added to browse mode, and enabled conditionally. Some of this can be migrated from the existing edit screen template, namely save and cancel buttons. A toolbar will be added to the layout view in edit mode. @charlesh88 will do a first pass of the markup required for this, which will be incorporated into these changes. 

The drag and drop gesture will trigger the switch to edit mode. This will require a change to the current policy that is preventing dragging and dropping an object into a browse-mode view.

**Comment by larkin** [comment]
Short priority notes from tag up today:

1. create button should skip properties panel, go directly to edit mode, item is not saved until it is saved.
2. prevent navigation without saving.

Tentatively, tree view should hide everything inside of node currently being edited, and prevent taking actions on other objects.

**Comment by akhenry** [comment]
Disable context menu in edit mode

**Comment by charlesh88** [comment]
@akhenry I'm in progress fixing markup and CSS; work so far has been pushed to open199c, but I've broken plots and am working in open199d to fix them.

**Comment by charlesh88** [comment]
@akhenry Just wanted to call this out, apologize if you're already on it: we need to hide the edit "pencil" icon in the upper bar when edit mode is active, no matter how the user got to that mode.

**Comment by akhenry** [comment]
Propose that this issue is closed, and the branch renamed from open199. NEM has another ticket (#161) that is being used as an overall 'tracking' ticket, and the functionality described in this issue has been implemented in the prototype.

**Comment by akhenry** [comment]
Closing this ticket. NEM prototype is in nem_prototype branch
