### ISSUE TITLE
[Documentation] Images missing from tutorials

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#203]
Images from tutorials appear correctly in https://github.com/nasa/openmctweb/blob/master/docs/src/tutorials/index.md but do not appear in generated documentation at http://nasa.github.io/openmctweb/tutorials/

(This should be reproducible locally by running `npm run docs` and checking `target/docs` for the expected png files, but I have not verified this.)

**Comment by akhenry** [comment]
There are also some broken links in the guide which I'll look at as part of this.

**Comment by larkin** [comment]
Can we just run nomnoml in the front end javascript and get rid of the image compilation process?

As a follow-up, There are a number of static site generators and using one of those may be more time-efficient then writing our own site generation code / linking / etc.  options include:

* middleman: https://github.com/middleman/middleman (open ended)
* jekyll: https://jekyllrb.com (static with blog capabilities)
* slate: https://github.com/tripit/slate (meant for api documentation)

**Comment by larkin** [comment]
@VWoeltjen above comment was about using some alternative static site generators, maybe break this out to a separate issue?

**Comment by akhenry** [comment]
Problem was in gendocs.js. The images (and html) are copied using node file streams. Was using encoding='utf-8' for text, and 'binary' for binary files. Binary encoding is treated differently in different versions of node so in some environments the images were being encoded as text. Have changed it to use null encoding for the images.

**Comment by akhenry** [comment]
Have created a separate issue for the broken links - https://github.com/nasa/openmctweb/issues/220
