### ISSUE TITLE
[Persistence] Create domain objects before persisting

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#215]
Per #139, change strategy for creating domain objects such that they are instantiated in-memory first, and then persisted for the first time via their `persistence` capability. (Currently, domain objects are created by persisting their model, then loading the object from the `objectService`.)

Benefit of this approach (from #139):

> it consolidates persistence-related code and has better long-term flexibility (makes it easier to support things like "temporary objects" which may or may not be saved.)

**Comment by akhenry** [comment]
This actually has implications for  https://github.com/nasa/openmctweb/issues/199 and potentially the implementation of https://github.com/nasa/openmctweb/issues/128 . #128 is nearly done, but might benefit from refactoring to incorporate changes from this ticket when it is implemented

**Comment by larkin** [comment]
@akhenry good note, but best to ship this and refactor this after #128 is shipped, so that we get something shipped and can get feedback on the interaction pattern before we spend time refactoring.

**Comment by akhenry** [comment]
@larkin Totally agree, #128 is very much a prototype, I would do a quite a bit of refactoring before merging into master.

**Comment by akhenry** [comment]
Agree. There's quite a bit of refactoring required with #128 it's very much a prototype at the moment.

**Comment by VWoeltjen** [comment]
Working on in current sprint, since this appears useful for #245
