### ISSUE TITLE
Modify WARP for new limits CSS approach

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmctweb#217]
Filing here (instead of JIRA) because I don't have time to VPN right now - will recreate as a JIRA issue.
https://github.com/nasa/openmctweb/pull/216

**Comment by VWoeltjen** [comment]
Think the only change here would be to CSS classes for limits (as was done for sine wave generator) - is that correct? If so, I can resolve this in the context of integrating #216

**Comment by charlesh88** [comment]
The change would actually be modding the way the CSS is applied by JS - if that's what you mean, then yes. Again, from #216:
> Changes the way limit CSS classes are applied: now uses 2 classes instead of one: Apply "s-limit-red" or "s-limit-yellow" to a tr element, or directly to any block element. When applied to a tr, the whole row will be colored, and a glyph icon will be added to the first cell of the row. For upper and lower limits, apply "s-limit-upr" and "s-limit-lwr" as a separate class.

**Comment by charlesh88** [comment]
Double checked warp-master: classes being applied in /warp/telemetry/src/capabilities/WARPLimitCapability.js are using correct form. Closing.
