### ISSUE TITLE
[Plot] Domain/range switching not working

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#218]
Moved from WTD-1179

Domain & range selectors in plot do not appear. Changes from #204 should make these visible again, but they do not cause the plot to be redrawn with the appropriate domains/ranges.

Need to consider how this works with the time conductor. Think that, when time conductor is present (or, more generally, when a plot has its domain selected internally) its own selector for domain should be suppressed, but the selector for ranges (e.g. DN/EU) should still be available.

**Comment by VWoeltjen** [comment]
@charlesh88 - do interactions with time conductor described above sound reasonable?

**Comment by larkin** [comment]
I think suppressing domain selection would be unnecessary.  I imagine any time a time conductor updates it can override current domain selection for all views, and then views can manually switch domain separately, but time conductor temporarily overrides that.

There have been discussions about "components excluding themselves from the time conductor," but not sure what that would look like.  I'd prefer to let users experience this behavior and tell us if they'd prefer something different.

**Comment by VWoeltjen** [comment]
That makes sense. My only hesitance there is that switching from a non-UTC domain to a UTC domain (and vice versa) could lead to strange results in cases where there is not a meaningful correlation between their numeric values. But we have that issue in time conductor, too, so may as well be consistent; the use cases for non-time-like domains in plot are uncommon at best so it may be some time before we run into this in practice.

**Comment by charlesh88** [comment]
Yes, I think that makes sense. The model here is that when the time conductor is conducting, the rest of the orchestra obeys. As we know, we’ll have to allow users to have gestures that allow an individual component to break free when needed, but we’re not there yet, yes?
