### ISSUE TITLE
[Representation] Avoid reuse of scope

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#227]
Avoid reuse of scope for the contents of an `mct-include` or `mct-representation` directive. Each time either they key changes, or the represented domain object changes, a new scope should be instantiated.

**Comment by VWoeltjen** [comment]
See [comment thread](https://github.com/nasa/openmctweb/pull/222#discussion_r43534255) on #222 for notes on how this might be accomplished.

**Comment by larkin** [comment]
Layouts significantly amplify the problem; with time conductor deactivated, when a layout contains plots, navigating away from the layout instantiates additional gl contexts, and continues to send telemetry requests in the background indefinitely; and each time you view the layout and then navigate away, it starts sending even more requests.

**Comment by VWoeltjen** [comment]
Reuse of scope eliminated on branch open227

Currently looking at removing redundant reinstantiation of templates, although that may be more of a concern for #229

**Comment by VWoeltjen** [comment]
Still getting two instantiations of PlotController per view switch. Based on observing the ids in the scope hierarchy of these plots, it appears that different `mct-representation` instances are responsible for each instantiation. Thinking there's a brief moment where the inner area of some container gets updated to reflect a new object/view pair, before its outer container gets recreated around the same. Still not sure what the root cause of this would be, but believe it may be external to `mct-representation`
