### ISSUE TITLE
[Core] Catch exceptions in topic

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#231]
From the `topic` service, catch any errors which occur when notifying listeners and log the associated messages at the `error` level (since it cannot be known from `topic` how critical these errors are)

This came up for the bug fixed by #205, where a mutation listener threw an exception. While that specific exception has been fixed, from [a comment](https://github.com/nasa/openmctweb/pull/207#issuecomment-151219179) on #207 we know that the fault was poorly-isolated and had the consequence of disrupting an unrelated operation (persistence, in that case - created objects could not be seen on reload in that case)

**Comment by larkin** [comment]
Makes sense in this context; As topics are intended to facilitate decoupling, it's important that this decoupling be fault tolerant.  Search indexing was not a vital operation and should not have broken persistence (as observed in #207).
