### ISSUE TITLE
Search filter menu does not work

### ISSUE THREAD

**Issue by larkin** [nasa/openmctweb#234]
Clicking the disclosure triangle that triggers the search filter menu does not show anything.  The expected behavior is it would show a list of types that you can filter the search results by.

Quick checking shows that this bug was not present in https://github.com/nasa/openmctweb/commit/4abb48abd8b01856328f6fa770e1abf1ba202bf5, but that it is present in https://github.com/nasa/openmctweb/commit/ec56fe7bfd1610cafbfce14d87b242ba01b3ddb9.

This bug appears to have been introduced with the resolution for #195 .

**Comment by larkin** [comment]
@VWoeltjen sending this your way because it appears to have been introduced by #195.

**Comment by RCarvalhoNASA** [comment]
Testathon 20151123:  Verified this works now
