### ISSUE TITLE
[Themes] Allow themes to be split across bundles

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#241]
From comments on #208:

* Need to be able to vary themes (at configuration time, eventually at run-time)
* Want bundles for specific features (e.g. timelines) to be able to include their own CSS (existing capability, don't want to lose)
* Need to do feature-specific CSS that is dependent on current theme.

In other words, a bundle should be able to add CSS that is specific to a theme. Currently, there is no notion of a "theme" in platform; the closest way to do this would be to include an additional theme bundle for each plugin that needs to introduce its own CSS.

Propose to solve this by adding an optional `theme` property to `stylesheets` extensions, and a `THEME` constant (default value = `espresso`, can be overridden by other bundles, e.g. to `snow`)

If this property is present, the stylesheet will only be loaded if the `theme` matches the globally defined `THEME` constant.

If this property is absent, the stylesheet will always be loaded.

Priority ordering would be enforced consistently across stylesheets regardless of theme; mismatched themes would be omitted, but otherwise the order of stylesheets would be the same as if this property did not exist.

**Comment by charlesh88** [comment]
I think this is great, it keeps the clutter out of bundles.json with a feature bundle not having to declare itself *and* its theme styling as a separate bundle. From your email, would look like this:
`"stylesheets": [
    {
        "stylesheetUrl": "css/timeline.css"
    },
    {
        "stylesheetUrl": "css/timeline-snow.css",
        "theme": "snow"
    },
    {
        "stylesheetUrl": "css/timeline-espresso.css",
        "theme": "espresso"
    }
]
`
Some questions:
- Where is the global theme defined? Ideally that's in a readily accessible high level config file (like bundles.json?). Guess that doesn't matter that much, as long as it's something I can change relatively easily during development.
- If a global theme isn't defined, none of the per feature CSS theme sheets would match, so they wouldn't be loaded, yes?

**Comment by VWoeltjen** [comment]
>    Where is the global theme defined? Ideally that's in a readily accessible high level config file (like bundles.json?). Guess that doesn't matter that much, as long as it's something I can change relatively easily during development.

Global theme would be declared as a constant, so any bundle could declare this. Priority would determine which definition wins.

>     If a global theme isn't defined, none of the per feature CSS theme sheets would match, so they wouldn't be loaded, yes?

That's correct. 

I think to minimize the delta, I'd keep the theme bundles in place and have each define this constant with their own value. In the future, though, we could move CSS for both themes into a single bundle and condition them on this constant.
