### ISSUE TITLE
[Persistence] Allow multiple persistence stores

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#245]
Support multiple persistence stores, with persistent location chosen based on location within the object hierarchy. (Fine to limit this for root-level objects initially, but not necessary.)

As an example, should be able to support a configuration with two roots:

* My Database
* My Browser

...where domain objects located within My Database get read from & written to an ElasticSearch database, and domain objects located within My Browser use browser local storage.

**Comment by VWoeltjen** [comment]
Sketch of a proposed solution to this:

# Multiple Persistence Stores

Desired behavior in user interface: Root-level objects (may) correspond
to different persistence stores. When an object is created or moved, it
is added to the appropriate persistence store based on its location.

## Operations

Operations which need to take this behavior into account:

* Creation. A created object must be located in an appropriate persistence
  store for its location.
* Reading. An object may be read back from one of several persistence stores.
* Update. An object should be persisted to whichever persistence store is
  relevant to it at the time it is persisted.
* Deletion. Punt on this for now, although this does mean being smart about
  reading objects back from persistence.

## Model

When an object is persisted, it should be persisted to the same persistence
store as its locating object (the object referred to by its `location`
property.)

Exceptions to this are domain objects which have a fixed persistence store
associated with them. That this latter category of objects exists only at
the root level is left as a configuration detail.

## Implementation

A shared concept among these operations a persistence table, which maps
domain object identifiers to the persistence spaces which contain them.

### Creation

When an object is created:

* Inspect its location to determine its persistence space.
* Update the persistence table for the newly-created object.
* Persist to that space.

### Reading

On initialization, build up a table among all persistence stores which may
contain domain object models. Should map from identifier to space.

If an identifier is present in multiple stores, compare `persisted`
timestamps and consider its space to be the most recently-persisted version.

When an object is read:

* Consult the persistence table to determine which space to read from.
* Read from that space.

### Update

When an object is saved:

* Inspect its location, and determine its persistence store.
  * This should occur recursively, with the base case being
    root-level objects with explicitly-defined persistence
    stores. Absence of this base case may either be considered
    an error, or may fall back to using the default persistence
    store, as appropriate.
  * Update the persistence table.
  * Persist to that store.

**Comment by VWoeltjen** [comment]
Note that the above does not keep things in sync in cases of concurrent editing. Consider this okay since this is part of a more general problem we intend to solve with Auto-Refresh at a future time. Would like to implement this in a fashion that such a solution becomes obvious/automatic when automatic refresh is implemented.

**Comment by VWoeltjen** [comment]
The approach described above does not necessarily work with more complex operations:

* Duplicate: Ordering of this action is currently subject to change, but may be implemented such that most deeply-nested objects get persisted _first_, which may mean their immediate parents don't have space mappings available yet (and may indeed not even be created)
* Move: All objects located by the moved object (even indirectly) need to be updated when its space changes.

**Comment by VWoeltjen** [comment]
A brute-force approach to the cases above:

* After an object (Object X) is persisted, query through its composition and identify which objects are in an incorrect store. Persist those.
  * A new persist call should trigger a change in store for that object, and recursively do so for any object it contains.
* To clean up in case the above is interrupted, whenever an object is read, detect whether or not it is in the expected persistence store (based on its location). If it is in the incorrect store, persist it to the correct one (in turn triggering the above.)

For a single user, this should be transparent (objects that were not moved to the correct store because of sudden shutdown will get moved next time they see them.) For other users, these may appear as missing objects until that happened. Could consider having automated background processes server-side which crawl the object hierarchy and move documents into the appropriate scores when data integrity violations are detected, but don't want to deal with that now

**Comment by larkin** [comment]
brute force and total overkill-- duplicate action could handle this with a small change in code, by reading the persistence space from the destination and applying that to the individual persist calls.

For Move and Link, I think these would just work, though we may eventually need some policy that controls whether or not linking is allowed from one persistence space to another.  If we can't link between spaces, we can't move either.  I think in some cases, linking between spaces is fine, but in others (say linking an object in user's personal space to a shared space), it is bad.

**Comment by VWoeltjen** [comment]
Link would just work, but Move is problematic. Say your roots are A and B in the following hierarchy, each of which corresponds to a different persistence space. For simplicity, nothing here is a link.

* A
* B
  * C
    * D
    * E

Move C to A. As currently implemented, that's a mutation to B and A (to change composition) and to C (to change location). D & E are untouched, meaning they continue to reside in the persistence store associated with B - not what is wanted!

Getting Duplicate right is easier if you just change Duplicate, but (a) don't want to step on work for #128, (b) if every action that interacts with persistence needs to worry about these details, that's poor separation of concerns (which results in problems like (a)). Want to localize the decision-making process about where things get persisted so that we only have to maintain these rules in one place. 

That said, duplicating by creating everything in the wrong space and then moving it to the right one is a bad approach, so I expect API changes will be necessary, such that Duplicate can talk to something that can make these decisions correctly

**Comment by VWoeltjen** [comment]
> If we can't link between spaces, we can't move either. I think in some cases, linking between spaces is fine, but in others (say linking an object in user's personal space to a shared space), it is bad.

My going-in position is to allow linking anywhere; if you don't have permissions you get a "missing object." Keep in mind that this isn't as simple as suppressing the link action - if you move something that contains links, you can still wind up in this situation.

Disallowing move when a link is disallowed makes developer-sense (since a Move is a Link-Plus) but makes poor user-sense; even if you don't want to Create Link from a private space into a public space, you definitely want to Move from a private space into a public space. That's one of the primary use cases for private spaces, to work on things until you are ready to publish them. It's true that you could Duplicate instead, but that's not the action you'd be looking for - you'd want to do a Move. (It's tempting to implement Move as a Duplicate + Remove in this case, but that will cause any existing links to break.)

**Comment by larkin** [comment]
@VWoeltjen Just because #128 is in progress, I don't think we should implement a workaround when we could just ignore it in the context of this ticket and support with much less effort at a later date.  Don't want to write a not-insignificant amount of code that we plan to remove later.

In that vein, a very simple option is to prevent actions between persistence stores and re-enable support for them later.  We don't need actions between persistence stores at this time.

When we do get to actions between persistence stores...
* Link: ok
* Duplicate: ok
* Move: `move` is currently a `remove` and then a `link`, which, as discussed, works just fine in the same persistence store.  However, `move` from one store to another could be a `remove` followed by a `duplicate`, and would borrow the blocking behavior that duplicate currently has.

**Comment by larkin** [comment]
I'm not sure how you'd prevent a cross-persistence store move from breaking links to that thing.  When all you have is an id, how do you tell which store to load it from?

**Comment by larkin** [comment]
....
link across stores seems to have the same issue.  composition contains an id, how do you know which space to load it from?

**Comment by VWoeltjen** [comment]
Same problem occurs for reading generally (isn't unique to link, move, etc)

Approach I'm looking at using for this (from above):

>  On initialization, build up a table among all persistence stores which may
contain domain object models. Should map from identifier to space.

> If an identifier is present in multiple stores, compare persisted
timestamps and consider its space to be the most recently-persisted version.

**Comment by larkin** [comment]
though unlikely, it seems that the same identifier can exist in two places and these should not be considered to be the same object.  They'd be the same if we moved objects, which would be odd.

Also seems significantly slow if each load from the persistence has to consult `n` different persistence spaces.  Some hinting as to which persistence space contains an object seems ideal.  Especially when we know there will be 3-4 active persistence spaces in some VISTA configurations.

hrm, also presents an option to move taxonomy model providers to a persistence space instead of model service...

**Comment by larkin** [comment]
After review, I think the main issue with consulting all persistence stores is the performance one.  Composition loads will be impacted pretty negatively, search indexing will collapse.

**Comment by VWoeltjen** [comment]
That's why I'm saying we should build that table:
 
> On initialization

It's `n` requests to build the initial table for `n` persistence stores, then one request per object to read.

It's true that this table will fall out of sync if there is concurrent editing, but that will happen anyway in the absence of auto-refresh.

**Comment by larkin** [comment]
So you're saying that on initialization, we will read every persisted object from every store and store the id of each object in each store? Seems like a lot of up front work.

**Comment by VWoeltjen** [comment]
On initialization, we will read a list of identifiers from each persistence store. You only need to load models if IDs occur in multiple stores (to find the most recent.)

There's a `listObjects(space : string) : Promise.<Array.<string>>` method on `PersistenceService` for this case (which may be unimplemented for most providers)

For any of our providers, `listObjects` is a single HTTP request.

**Comment by larkin** [comment]
Seems complicated and prone to breakage. Hinted ids would allow persistence service to choose what is best. No hinting? Use the default. 

Seeing as persistence stores will likely have a unique key, hinting could be a prefix. 

Otherwise we have to maintain an in memory list, update it on all operations, etc. it's a lot of book keeping that isn't necessary.

**Comment by VWoeltjen** [comment]
I don't think it's all that complicated (it's a table and a decorator) but yes, does create an opportunity for strange behavior.

Encoding persistence spaces in identifiers does make things look a bit simpler near-term:

## Implementation

The concept here is that a domain object's identifier should encode its
persistence space, e.g. in a prefix. Unprefixed identifiers should reside
in a default persistence store.

### Creation

When an object is created:

* Inspect its location's identifier to determine its persistence space.
* Generate an identifier with the same prefix.
* Persist to that location.

### Reading

When an object is read:

* Inspect its identifier to determine which space it comes from.
* Read from that space.

### Update

When an object is saved:

* Inspect its identifier to determine which space it comes from.
* Update the object in that space.

------

There are drawbacks to this approach:

* Not a clear way to add in the creation-time behavior currently (can't just do that with a decorator.) Would need to refactor create, probably duplicate as well, to behave appropriately here.
  * ...preferably by moving some of the implementation details of creation/duplication behind an interface (e.g. a `creation` capability) so that user code can just say "I'm creating something using this object." The "...and this means putting it in the same space as that object" part does not need to be repeated.
    * ...which has the nice benefit of making Duplicate put things in the right place quite easily.
* Moving objects from space to space becomes difficult. A whole tree of identifiers needs to get rewritten in the move; could do this as a duplicate + delete, but would break links everywhere.
  * We can temporarily disable move/link between spaces to punt on this, but moving from space to space is an important use case that we'll have to solve.

@larkin - thoughts on the case of Move? Agree that encoding persistence spaces in identifiers will be less error-prone, but am hesitant to go down that path if we're going to hit a wall trying to support the "move something from my private area to a public area" use case. So far the best option I see is to implement a cross-space Move as Duplicate + Remove in order to make this work, perhaps with a warning about whatever weird behavior may ensue for existing links?

**Comment by larkin** [comment]
I think move will be complicated no matter what; disabling it seems safe short term as our current multiple persistence store use case is shared persistence spaces per mission, and not otherwise public/private. 

When private storage becomes a thing, we can do a full implementation of move, and we can choose whether to break links or to update all links with new ids. 

Perhaps at that time we find a more resilient solution for syncing client and server side state a la falcor, relay, or something similar-- something that makes batch persistence easy. Whether or not that thing exists, who knows.

**Comment by VWoeltjen** [comment]
Working on #215 now to feed into this (want to stick object creation behind a capability, such that persistence space can vary at creation time)
