### ISSUE TITLE
[TimeConductor] Difficult to specify time ranges

### ISSUE THREAD

**Issue by larkin** [nasa/openmctweb#259]
When entering time ranges into the text entry fields, when typing in the end field, the start field can be overridden, and when trying in the start field, the end field can be overridden.  Seems that input constraints about time conductor should not be applied while the user is typing-- especially when they've already entered a specific date in the other date field.

Here's a gif explaining the issue, as I try and enter the time range "2015-209 to 2015-210":

![tc-date-clobbering](https://cloud.githubusercontent.com/assets/226503/11006781/90d52cdc-847a-11e5-91e5-6b72a02acfa1.gif)

**Comment by VWoeltjen** [comment]
Assigning to Charles to specify correct behavior here (e.g. when _should_ constraints be applied?), reassign to me once that's available

**Comment by charlesh88** [comment]
**NOTES IN PROGRESS:**
Making sure I understand: the user can essentially enter a start value that's after the current end value, right? And I assume, vice versa with the end datetime? 
Looking at a couple existing examples:
- Kayak.com: entering a start after the end will bump the end by a default minimum. End before start entry is reset to the default minimum as soon as the field focus is blurred.
- Southwest.com: cheerfully lets you key in end before start and vice versa; fields display error on submit.
- Virgin: can't manually enter dates, only use picker.

**Comment by larkin** [comment]
I think the issue here is when is the date "entered," from a user's perspective, and when should the logic for the start date applied? 

What currently happens is that with each keystroke, the resulting date is evaluated, and the logic for ensuring an offset between start and end is applied.  So if you've entered "2015-209" as the start date and you're entering "2015-210" as the end date, once you have entered "2015-2 it evaluates it as "2015-002 00:00:00.0000" and applies the constraint to the start date, pushing it back.  You then continue typing in the complete end date of "2015-210" and notice that the start date is no longer the date that you entered.

The updates to the start date are being applied upon each keystroke, when they should really be applied once, when the input field loses focus.

**Comment by VWoeltjen** [comment]
> the user can essentially enter a start value that's after the current end value, right? And I assume, vice versa with the end datetime? 

Problem is almost the opposite. Current behavior is fairly similar to Kayak.com, except we handle both Start and End in the same way that Kayak handles starts.

The problem that's being illustrated above:
1. User enters "2015-209" in Start
  a. This is before the End time, so no minimums get enforced - change to start has no effect on end
1. User enters "2015-210" in End
  a. ...but in the process of typing this, they will have typed "2015-2", which is also a valid date; this is before the start time, so the start time gets adjusted accordingly (in the GIF, I think this happens as soon as the user enters "2" - we could solve that by parsing dates more restrictively, but will still hit trouble at "2015-2").

I think a similar approach to what Kayak does (treating End different from Start) would work here, e.g.:

* While changing Start, if the "minimum duration" constraint is violated, update the end time to be Start + the minimum.
* While changing End, if the "minimum duration" constraint is violated, turn the field red and don't update the actual value in use (but don't do anything to the text field contents while the user is typing)
* On tab out of any field that is in an invalid state, revert it to the underlying actual value in use (this would be more Kayak-like)

**Comment by charlesh88** [comment]
@VWoeltjen @larkin @akhenry 

Datetime entries really just have two evaluation criteria: 
**Form**: is it well formed, is it a valid datetime in whatever is the currently selected time format? 
**Location**: Does a newly entered Start occur after the current End, does a newly entered End allow for a minimum duration span, etc.? Location evaluation is dependent on form being valid; therefore, form must always be evaluated *before* location. 

For a field to be fully valid, it must be well formed and well located. We should evaluate form *and* location as the user types, and visually feedback whether the entry is valid or not as the user types. I believe I’ve seen this actually working in the app. 

At time of tabbing out of a field, we will need to do some things. I propose this for what to do when the just-blurred field is invalid:
Rule 1: if form is invalid, revert the just-blurred field back to its previous value.
Rule 2: if the location is invalid, then bump the *other* field as needed.

In short: on tab out, an invalid form in the just-blurred field gets reverted to its last good value, while an invalid location forces the other field to comply. This model is based on the idea that the *last* action the user is took is what they want to apply as an effect.

Here are some use cases that exercise these rules:

ID | Case | User Typing Into | While Typing in Focused Field | Tab Out of Focused Field
------ | ------ | ------ | ------ | ------
1 | Valid datetime form | Start | Field visually indicates validity | Nothing
2 | Valid datetime form | End | Field visually indicates validity | Nothing
3 | Invalid datetime form | Start | Field visually indicates invalidity | Revert Start to previous value
4 | Invalid datetime form | End | Field visually indicates invalidity | Revert End to previous value
5 | Start is after End | Start | Field visually indicates invalidity | Automatically change End to Start plus minimum duration
6 | End is before Start | End | Field visually indicates invalidity | Automatically change Start to End minus minimum duration
7 | Start is before End, but duration < minimum duration | Start | Field visually indicates invalidity | Same as 6
8 | End is after Start, but duration < minimum duration | End | Field visually indicates invalidity | Same as 5
9 | End is set to the last possible tick that the application can support; the user enters a Start value < minimum duration | Start | Field visually indicates invalidity | Can't set End beyond the end of time. Either the universe ends, or we adjust the Start
10 | Start is set to the first possible tick that the application can support; the user enters a End value < minimum duration | End | Field visually indicates invalidity | Can't set Start before the end of time. Either the universe ends, or we adjust the End

Thoughts?

**Comment by akhenry** [comment]
@larkin I love the gif demonstration! What sorcery is this?

**Comment by larkin** [comment]
@akhenry quicktime screen capture, then ffmpeg to convert to gif, in this case `ffmpeg -i TC-date-clobbering.mov -pix_fmt rgb24 tc-date-clobbering.gif`.

**Comment by VWoeltjen** [comment]
> Thoughts? 

Makes sense to me. In the case of valid input, does this mean that the change should only be applied to the rest of the control on blur? I think so (and it would simplify implementation if so) but want to verify

In the table, this would look like:


ID | Case | User Typing Into | While Typing in Focused Field | Tab Out of Focused Field
------ | ------ | ------ | ------ | ------
1 | Valid datetime form. | Start | Field visually indicates validity. | Change is applied to surrounding control.
2 | Valid datetime form. | End | Field visually indicates validity. | Change is applied to surrounding control.

As a consequence, you wouldn't see the right edge of the time-range-slider update to reflect the new outer bounds change until _after_ tabbing out of the relevant field.

**Comment by larkin** [comment]
Blur is the correct event here; it's not only triggered by a tab out, but by all possible causes that generally indicate "I'm done with this field".  I think this should be applied at the mct-control level; perhaps it $emits an event upwards on blur?  

Also: may be worth wrapping both mct-controls into a form tag and handling it via standard form submit lifecycle.  That way, a user pressing the return key in an input field will submit the form.  Might add an additional handler on the time conductor that triggers a form submit on blur.  I can't recall if this will cause submit to be triggered twice when the user presses enter.

Note that wrapping mct-controls in a form would be very useful in other places such as the edit properties dialog: it bothers me that I have to click the "save" button when creating an object; I'd much rather press "enter" and have it save for me.
