### ISSUE TITLE
View switcher menu not appearing

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmctweb#260]
Originally https://github.jpl.nasa.gov/MissionControl/vista/issues/132.
View switcher menu in the main object view area is not displaying its menu when clicked. The issue is related to a regression caused by a fix in open90 to keep the browse bar elements from laying out badly when when a user opens both left and right panes when in a small window area.

**Comment by charlesh88** [comment]
@larkin @VWoeltjen If you guys really need this fix in a hurry, let me know. Otherwise I think I'll be ready to do a pull request by end of Monday 11/9. The right solution was bound up in a move to flex layout; the view switcher menu was being hidden because it's in an element that recently was changed to use 'overflow: hidden'. If you like, take a look at open250 and comments in #250.

Major work on this pushed to open250.
To-dos #260:
- Double-check that essential elements have not been broken
- Double-check more in mobile

**Comment by larkin** [comment]
End of day fix for this would be ideal; otherwise it will cause problems in presentation preparation this afternoon.

**Comment by charlesh88** [comment]
Pushed fixed snow/_constants file to open250 with fd135a16af17e12085cfc1742b04ea0334c0fca1

**Comment by charlesh88** [comment]
Markup and CSS modified for a fairly significant redo of .object-browse-bar and markup in object-header.html to use .l-flex-row CSS. Unit tested fairly extensively in Chrome and its mobile simulator; was not able to test on actual mobile device.

#274 created as a pull request for this.

**Comment by RCarvalhoNASA** [comment]
Testathon 20151123:  This appears to be working correctly
