### ISSUE TITLE
[Edit Mode] Disallow context menu actions on tree items during edit mode.

### ISSUE THREAD

**Issue by akhenry** [nasa/openmctweb#277]
Item 1. from https://github.com/nasa/openmctweb/issues/161#issuecomment-155162928

In order to prevent the object tree on the left hand side, and the object being edited on the right hand side from getting out of sync, context menus (and thus editing) of objects in the tree should be disabled when edit mode is enabled.

**Comment by charlesh88** [comment]
See pg 22 of UI sketches: https://drive.google.com/a/nasa.gov/file/d/0B0v27OM1JkSeR001RFJZMk43QVk/view?usp=sharing

**Comment by akhenry** [comment]
>I'd say disallow all or disallow none at the start. We could try user-testing with these enabled; the problem here (observed in MCT on the desktop) is that there can be cases where it is not clear to the user that the stuff on the left is saved, and the stuff on the right is unsaved. The New Edit Mode border might disambiguate this sufficiently, or it might not.
@VWoeltjen

**Comment by akhenry** [comment]
Have pushed a branch Open277 that implements this. Have also merged into NEM master branch 'Open199'.

### Summary of changes
Added a check in `ContextMenuAction.perform` that inspects the currently navigated item in `NavigationService` to see whether it is editable (ie. `hasCapability('editor')`).
