### ISSUE TITLE
[Edit Mode] Visual indication of object being edited

### ISSUE THREAD

**Issue by akhenry** [nasa/openmctweb#278]
From https://github.com/nasa/openmctweb/issues/161#issuecomment-155162928 no 2.

While in edit mode, flag the currently selected item (as well as all linked instances of the object currently being edited) in the tree with a "pending update" visual status. This requires some UI design.

### Comments

>As simple as a CSS class, styling could be updated and iterated on. "dirty object" isn't a user concern, but "currently being edited" is; we shouldn't spend too much time on this for v1.
@larkin

> I'd broaden this to include any objects that have unsaved changes from Edit mode, including their links (not just the selected object.) This happens often in a timeline, but can happen in a Layout too (you can Edit Properties on a panel in a layout)
@VWoeltjen

**Comment by charlesh88** [comment]
See pg 22 of UI sketches: https://drive.google.com/a/nasa.gov/file/d/0B0v27OM1JkSeR001RFJZMk43QVk/view?usp=sharing

**Comment by charlesh88** [comment]
Charles will stub in a CSS class for this.

**Comment by charlesh88** [comment]
Beginning work on this in a new branch, based on open199: open278. I merged in the latest from open199-meet-open279 branch.

**Comment by charlesh88** [comment]
CSS should be able take are of the following:
* Coloring the tree node and adding an icon.
* Hiding the sub-tree for that element.
* Hiding the expand/collapse toggle.
* Turning off the click and dragging behaviors on tree items, using CSS pointer-events: none.

This should take care of all the visual indication and interaction handling that we need. All that remains would be applying a class to all tree items (originals and links) when an object is being edited.

**Comment by larkin** [comment]
Now that's what I'm talking about!  That's the sort of concerns that are best handled in CSS.

**Comment by akhenry** [comment]
So from the javascript side of things, tree nodes will need to somehow know whether they are the object currently being edited. I'm keen to come up with a solution that avoids creating _n_ new watches for tree size _n_ - which can become arbitrarily large. My current thinking is to use one-time bindings to add classes to each tree-node element with its object id (and for links, the object id of its original object). A single watch would be created (or actually a watch could be avoided entirely by using an observer) which would trigger a jquery (or native) class selection on the object id. This would pick up the original object and all of its links, and add a css class indicating that they are the object being edited.

It's not very angular, and it requires a dom traversal, but it's the most performant solution I could think of?

**Comment by larkin** [comment]
I think that's fine.  I would recommend using a data attribute to indicate the id instead of a css class-- it's possible to use data attributes as a selector and doesn't pollute class strings.  Then, when edit mode begins, you can select all elements with the data id via `document.querySelectorAll('[data-domain-object-id=123]')` and apply a class to those elements.

The only problem is that elements that are not in the DOM when edit mode begins would not get the class applied (i.e. expanding a tree node which contains a link to the object), but that is easy to resolve.

**Comment by VWoeltjen** [comment]
I have a similar problem on a closed-source (WARP) issue. There, we have a case where partial information is known about domain objects in the telemetry dictionary (you know a bit about the object from the identifier, which can be shown as a useful name, but don't know the contents.) The way we've displayed this is as a tree item with a little loading spinner where the type icon would normally be.

In that repository, this was handled by overriding the `label` template to check to see if an object was loaded and display this spinner conditionally. Aside from watch count, this approach was bad because it was sensitive to changes in platform; some recent markup/CSS changes in the tree cause that label to now display incorrectly.

The solution I'm working on there is to remove the custom template to allow things to be driven more by CSS. I've added a general purpose `status` capability which allows domain objects to be flagged with certain states, and a StatusRepresenter which converts these to CSS classes. #319 contains these changes, which I think could also be useful here. (`domainObject.getCapability('status').set('editing', true)` and all representations of that object now have a `l-status-editing` class; `domainObject.getCapability('status').set('editing', false)` and they don't.)

**Comment by charlesh88** [comment]
@akhenry I've pushed my finalized work here to open278 - this branch is ready to integrate with open199. I also did a safety merge with master and the most recent open278.

**Usage**
Add CSS class `active` via ng-class to tree-items and search-result-items. Specifically:
* Line 26 in /wtd-dev/platform/commonUI/general/res/templates/tree-node.html
* Line 24 in /wtd-dev/platform/search/res/templates/search-item.html

**Comment by akhenry** [comment]
@VWoeltjen I like this a lot. I think I'll go with this solution. Are you intending to do further work on #319 or am I good to merge this in to my NEM branch?

**Comment by VWoeltjen** [comment]
I think this should be safe to merge at this point; I do want to add tests and JSDoc, but that should merge in pretty cleanly later.

I'd also been thinking I'd look into reducing listener count, but I was thinking of [this comment](https://github.com/nasa/openmctweb/issues/278#issuecomment-157876513) which applies to a different situation. The number of listeners _called_ on a status change is small; the total number of active listeners is large-ish, but they're just sitting there in memory. I'll do a quick check of this with a large tree open and see if anything crazy happens, but I don't expect problems (in any event, should be able to hide any implementation changes behind the same interface.)

**Comment by akhenry** [comment]
So my initial implementation of this had an unindented consequence - all children of the edited object, including _their_ links, were also marked as being edited. The reason for this is EditableDomainObject and how it wraps any objects retrieved from capabilities as EditableDomainObjects as well. You can see this in action in branch open278-proto - https://github.com/nasa/openmctweb/tree/open278-proto

I want to check before I fix this whether this is actually wrong. What it's doing, in essence, is demarcating the boundary of all objects possibly affected by this edit, which is not necessarily a bad thing, especially when you take into account sub-object editing, which is on the cards for a future sprint.

I suspect it's too far-reaching at the moment. Sub-object editing will need to be handled in a similar way to #278 but probably only when that object is _explicitly_ edited.

Thoughts?

**Comment by larkin** [comment]
I think at this moment this is a bit broad-- interaction with sub objects should be allowed (e.g. you should be able to compose the same object multiple times into a parent).  If it can only be the parent object, perfect.

**Comment by akhenry** [comment]
Good point re: multi-composition.

So I've updated the open278 branch with only visual indication of the edited object and its links. 

@VWoeltjen raised an issue earlier about also marking any other objects dirtied during the course of editing. This falls somewhere in between the two approaches we've discussed above. It would mean however, that any child object that is edited (eg. via its properties) would be immediately disabled in the tree, preventing further composition with this object?

**Comment by larkin** [comment]
I think that's a concern of sub object editing and not part of the current feature.  We can work it out when we get there.

**Comment by VWoeltjen** [comment]
Agreed that we can defer a solution. My inclination would be to set the status on the Edited object when the `edit` action is performed, and to set status on sub-objects when they are dirtied. Doing the whole subtree on `edit` seems like overkill - what it's trying to communicate is correct, but to a user I'd expect that to be very visually confusing.

**Comment by akhenry** [comment]
Hi all, I've just pushed an update to open278. I have removed the hacks that were in it to work with the css definition using `active` instead of `s-status-editing`. I've moved this hack to the open278-proto branch if you still want to see visual indications working.

@charlesh88 This solution incorporates #319 which applies a class of `s-status-editing` to the representation itself (so a slightly different element than we were using with `active`). When you get a moment, would you mind pulling down open278 and modifying the css to use `s-status-editing` instead of `active`. Once that's done, #278 is completed. 

We will need to make this change in `browse-object.html` as well, but I'm happy to defer that for now, as it will require a little code refactoring in open199. Thanks!

**Comment by VWoeltjen** [comment]
One quick note on this - the `s-status-editing` class is going to get applied to _every_ representation of the edited domain object, not just the ones in the tree. Think this is what we want (leaves it to CSS to decide where and how visual changes should be applied) but it's worth being aware of; a CSS rule for just `.s-status-editing` will probably have broader consequences than intended.

**Comment by akhenry** [comment]
@VWoeltjen yep, thanks for raising this. I think it's totally what we want. It will be super useful to have all representations exposing the status of their underlying object in a way that allows for simple css styling of object state.

**Comment by larkin** [comment]
Totally, using fake class names, selectors could be like so:
* `.s-tree-node .s-status-editing`: In tree, disable pointer events/hide child nodes.
* `s-browse-object .s-status-editing`: in browse pane, show blue highlight/other status tweaks.

**Comment by akhenry** [comment]
Assigned back to @charlesh88 for s-status-editing support.

**Comment by akhenry** [comment]
@charlesh88 I've created a temporary branch with a modified the scss rule just for the active tree elements, and pushed to [open199-css](https://github.com/nasa/openmctweb/tree/open199-css). It's just to facilitate testing for now. So there's no rush to get to this, but it should be reimplemented properly in open199.

I just changed [one line](https://github.com/nasa/openmctweb/blob/open199-css/platform/commonUI/general/res/sass/tree/_tree.scss#L147) in _tree.scss .

**Comment by charlesh88** [comment]
As discussed, will effect changes in fork of open199.

**Comment by charlesh88** [comment]
Needed mods for s-status-editing pushed to open199e; #389 added as a pull request and assigned to Andrew.

**Comment by charlesh88** [comment]
Andrew, can you close this after we determine that open199e contains what we need?

**Comment by akhenry** [comment]
Yup, will do. 

Thanks!

**Comment by akhenry** [comment]
@charlesh88 Almost there. Only problem is that the dialogs launched from the context menu in the element pool have the CSS magic applied, so you are not able to expand them etc.

eg. Edit a layout with some objects in it, and then attempt to create a link in one of them. The dialog launched will show the object being edited, but it's disabled by CSS so it can't be expanded etc.

**Comment by akhenry** [comment]
@charlesh88 should I create a separate issue for https://github.com/nasa/openmctweb/issues/278#issuecomment-163054691 and close this?

**Comment by akhenry** [comment]
Reassigned to @charlesh88 to take a look at https://github.com/nasa/openmctweb/issues/278#issuecomment-163054691

**Comment by charlesh88** [comment]
The problem here specifically is that when we're editing, the root node in the Create Link overlay is being set to the object currently being edited. We don't actually want the user to modify the current object, so the display is actually correct.
The bigger issue here is that we what we really want is a subset of the context menu items (Remove, Edit Properties), but we don't have time to do that. Could we just disable the context menu entirely for Elements pool items? Given that we have the toolbar with trash can to remove things, and that most items in that menu cause problems or don't work properly, I feel somewhat strongly that we should disable the context menu for those items. If that's difficult to do in code I can write some CSS that just hides the menu (hacky, yes).
@VWoeltjen @larkin @akhenry If anyone feels differently about this, please weigh in.

**Comment by larkin** [comment]
We don't have the toolbar to trash things in every view yet.  In fact, the layout (the prime concern to me) doesn't have it.  Nor does a panel in plot mode.  We need elements pool, but we don't need to make any changes to the implementation as part of NEM.

IMO, We should consider all of these elements pool related bugs follow-ups and not blockers.  They all currently exist before new edit mode.  we plan to overhaul handling of the elements pool which will resolve a lot of them, but that's not part of new edit mode-- to say so is to introduce massive feature creep.

**Comment by akhenry** [comment]
@larkin https://github.com/nasa/openmctweb/issues/278#issuecomment-163054691 is a new bug not present in old edit mode. It results in reduced functionality in NEM compared to OEM.

@charlesh88 is it possible to define the s-status-editing style rule with some context so that it applies in the navigation tree, but not the elements pool? If need be we could add a class to one of them to make it easier to differentiate

**Comment by VWoeltjen** [comment]
If we need to address before shipping NEM but want to confine the scope, how about a quick-fix:

* Suppress context menus in the elements pool
* Add a little Remove button next to each element in the elements pool

```html
<mct-include key="'action-button'"
    parameters="::{ action: containedObject.getCapability('action').getActions('remove')[0] }">
</mct-include>
```

Stick that right next to the `label` representation in the `ng-repeat` of the `elements` representation. Position with CSS (e.g. only show on hover?) Then work on higher-priority stuff until we can handle this the right way.

**Comment by larkin** [comment]
@akhenry I don't think we expected to use "create link" inside of new edit mode.  It's not expected usage.  So perhaps the objects are hidden, but the long term fix is to remove the button, so why spend time fixing it when it's going to be removed later?

**Comment by akhenry** [comment]
@VWoeltjen good solution.

An alternative, if we do want any of the other context menu items, might be to use EditableDomainObject's wrapping of capabilities to wrap ActionCapability and filter the Actions returned by it? That should be an easy fix.

**Comment by akhenry** [comment]
https://github.com/nasa/openmctweb/issues/278#issuecomment-163448311works. I have a context menu that shows "remove" and "edit properties". Edit Properties is kind of useful to have, and appears to work as expected (changes are not persisted until you hit save on the layout".

Go to original also works now without unceremoniously dumping you out of edit mode, but I've disabled it for now because I'm not sure it makes sense in edit mode?

**Comment by akhenry** [comment]
Closing after implementing solution https://github.com/nasa/openmctweb/issues/278#issuecomment-163448311

**Comment by charlesh88** [comment]
YOU DA MAN! Fantastic! Agree on Edit Properties as well as Remove. Go to Original doesn't seem to be useful from edit mode - let's leave it out for now, and if we hit use cases where it is useful we can bring it back.

Thanks again!
