### ISSUE TITLE
[Editing]  Enable toolbar during editing

### ISSUE THREAD

**Issue by akhenry** [nasa/openmctweb#283]
Taken from https://github.com/nasa/openmctweb/issues/161#issuecomment-155162928 No. 7

The edit mode toolbars need to be ported across from "old" edit mode.

**Comment by akhenry** [comment]
This is possibly a stupid question, but the only instance where I see a toolbar in old edit mode is when editing a telemetry panel in fixed position view. Is this correct?

**Comment by VWoeltjen** [comment]
Also used in timelines (which are not enabled pending resolution of #208)

**Comment by akhenry** [comment]
Oh right, cool. Thanks!

**Comment by akhenry** [comment]
@charlesh88 I am having some CSS challenges with this. The toolbar is now appearing in the DOM, but is not visible on screen. Would you mind taking a quick peek at the mct-toolbar element in browse-object.html? The easiest way to make it 'appear' is to edit a telemetry panel in fixed layout view.

The latest code has been pushed to Open199

Thanks!

**Comment by akhenry** [comment]
@charlesh88 Nevermind, whatever you did in #278 has fixed this issue in that branch :) So Open199 will pick it up when I merge in.

**Comment by akhenry** [comment]
Closing this issue as the prototype has been implemented in open199

**Comment by akhenry** [comment]
Reopening because of below issue:

* When in fixed layout in edit mode, toolbar button menus are hidden behind the grid as shown in screenshot below

![screen shot 2015-11-27 at 3 30 35 pm](https://cloud.githubusercontent.com/assets/4215777/11449276/11fc098e-9524-11e5-9ba9-8b14e3f60920.png)

In this image, the "Add" menu has been pressed, and the menu appears under the layout grid. Appears to be a z-order issue?

You can see this in action in the open199 branch.

**Comment by charlesh88** [comment]
Assigned to Charles to look into CSS z-index issues.

**Comment by charlesh88** [comment]
Fixed pushed to open283.

**Comment by charlesh88** [comment]
Fixed pushed to open283. Pull request filed with #360.
