### ISSUE TITLE
Fix markup and CSS in open199

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmctweb#293]
open #199
IN-PROGRESS
IMPORTANT: plots are not laying out correctly, need to figure out why
Work so far pushed to open199d

**Comment by akhenry** [comment]
Fixed edit mode button not working. I've pushed fix in open199c. Will wait for fixes to plots in Open199d, merge them back to c, make sure everything's working in c, then merge that back to open199. Oh my.

**Comment by charlesh88** [comment]
Good to hear. I'm on this first thing this morning.

**Comment by charlesh88** [comment]
@akhenry I merged your latest 199c into 199d this morning, and did my fixes. Save button works great now. Also tried to merge in master, but said I was up to date. You should be good to go at this point. I'm not going to file a pull request - you should follow your plan above.

**Comment by akhenry** [comment]
Ok, sounds good. Thanks Charles!

Andrew

**Comment by akhenry** [comment]
Have merged everything into 199, plots are looking good now.

It looks as though there is a layout problem with scrolling view on telemetry objects though. In Open199, viewing telemetry in scrolling mode shows no data. Inspecting the DOM however reveals that the table rows are populated, but the table seems to have zero(ish - can actually see a few pixels of limit violation indicators) height.

**Comment by charlesh88** [comment]
Crapola - see it too. Thanks!

**Comment by charlesh88** [comment]
@akhenry Just pushed a fix for this up to open199d.

**Comment by akhenry** [comment]
Looks good to me, thanks Charles.
