### ISSUE TITLE
Time Controller / Conductor date inputs no longer display picker when clicked

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmctweb#297]
Saw this in master today: clicking the calendar icon in the Time Controller doesn't display the picker anymore. Inspecting the rendered code, I see this:
![screen shot 2015-11-12 at 2 03 01 pm](https://cloud.githubusercontent.com/assets/1056412/11132674/25de4d20-8946-11e5-9e99-40ba06f3b867.png)
Note that what should be an mct-pop element is just a comment. It doesn't look like we deliberately disabled the pickers to me, did we? Here's the current source .html:
![screen shot 2015-11-12 at 2 01 46 pm](https://cloud.githubusercontent.com/assets/1056412/11132708/5da9e46c-8946-11e5-9795-7e4b0d749adb.png)
Wondering if this is an unforeseen result of #195.

**Comment by larkin** [comment]
I believe this was intentional as part of #181 and #182: some time formats do not map to the calendar picker; SOL being a big one.

**Comment by VWoeltjen** [comment]
There's a check for format in the template; the picker should show for `utc` timestamps

The icon which toggles this _is_ appearing, so not clear why the click isn't causing toggling to occur. Investigating now

**Comment by charlesh88** [comment]
Thanks. I'm definitely in UTC.

**Comment by VWoeltjen** [comment]
Looks like this was introduced in the context of #182; the `ng-if` creates a child scope, so the assignment to the toggle variable gets lost there. Nesting the assigned field in another object resolves the issue, will submit a PR shortly.

That said, I do also see that this is interacting poorly with other CSS changes:

![picker-z-indx](https://cloud.githubusercontent.com/assets/1685764/11133683/25fd8888-894c-11e5-9e0d-801e8cf06658.png)

I will include a workaround (add on an explicit `z-index: some big number` from `mct-popup`) and file a followup issue to resolve this correctly

**Comment by charlesh88** [comment]
Yep, I've having to move some z-indexing around lately. Note that the z-index spreadsheet is being kept up to date: https://docs.google.com/spreadsheets/d/1AzhUY0P3hLCfT8yPa2Cb1dwOOsQXBuSgCrOkhIoVm0A/edit#gid=0. 
If you want to throw a z-index of 70 to 79 for now that'd be fine but may not solve the problem; I am working in this markup right now, could you assign this over to me when you're done, esp. if you're still having trouble with the z-indexing.

**Comment by larkin** [comment]
@charlesh88 what if you defined all zindex values in a scss variables file similar to that spreadsheet?  Would reduce duplication and give you one place to look at to re-arrange zindex values.
