### ISSUE TITLE
[Representation] Representation data may become stale

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#302]
When navigating between two or more instances of the same domain object (e.g. from an original to a link, or between two links) representations may fail to detect this change and continue to use data from the old domain object. In some cases (the `context` capability) this data will be out-of-date and its usage will result in incorrect behavior.

For instance, if you have the tree:

* My Items
  * Folder A
    * Object B
  * Folder B
    * Object B&ast;

&ast; _a link_

You can take the following steps:

1. Expand Folder A and Folder B in the tree
2. Click Object B in Folder A to navigate to it
3. Click Object B in Folder B to navigate to it
4. Click the "back arrow" next to the title of Object B
5. Observe, we navigate to __Folder A__, when expected behavior was to navigate to __Folder B__

**Comment by VWoeltjen** [comment]
Putting in next sprint; have only been able to reproduce this with navigation from the back arrow, Remove (e.g. from the context menu arrow) effects the expected object.

**Comment by VWoeltjen** [comment]
Want to take care to avoid detecting changes that aren't actually changes.

**Comment by akhenry** [comment]
Verified that this is resolved in Baxter testathon.

**Comment by charlesh88** [comment]
Testathon 20151207: verified
