### ISSUE TITLE
[Clocks/Timers] Clock indicator shows in a collapsed state

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#304]
Due to changes to support notifications, the Clock indicator in the status area now appears simply as a clock icon; hovering over this causes the current time to appear.

Believe that desired behavior is that the current time is always visible. Candidate solutions:

* Add a property to `indicators` extension definitions which allows them to be flagged as "always visible", and include appropriate CSS classes to reflect this.
* Use a custom template for clocks which excludes classes which cause the text to collapse.
* Move the current time to a different part of the UI entirely (this may have only ended up in the status area for expediency)

Assigning initially to @charlesh88 to determine specifics of desired behavior, should reassign once ready to implement.

**Comment by charlesh88** [comment]
Yeah, I've been looking at this too, and had been thinking along the lines of your first suggestion, but see my note below. Gives us the most flexibility and options. I'd also like to be able to move the clock to the right, adjacent to the app logo. 

If we give the indicator the ability to specify a CSS classes string, that let's us do both things and more in the future.

**Comment by VWoeltjen** [comment]
I like that idea - down the road, we'd also be able to handle the glyph and its coloration with CSS classes in the same way, correct? That would be handy.

**Comment by charlesh88** [comment]
Exactly right. I'd like to get to the point where we remove glyph assignment from code completely, and instead just use classes for everything. It's then up to the CSS to determine the glyph, allowing different glyphs and fonts per theme.

**Comment by charlesh88** [comment]
Fix for now pushed to open336; PR filed as #421.
