### ISSUE TITLE
[Performance] Reduce watch counts in tree

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#315]
Utilizing changes from:

* #311 an `mct-refresh` directive
* #312 an `mct-observe` directive
* #313 change `ng-model` to `mct-model`
* #314 removal of two-way binding from `mct-representation` / `mct-include`

...reduce the watch counts associated with the `tree` representation of domain objects.

Based on prototyping (#303), believe the tree can be implemented with zero watches using the changes referenced above. Goal here should be to reach zero watches or to come as close as possible.

**Comment by VWoeltjen** [comment]
Resolved by #739 (taking an even less Angular approach than described here)

**Comment by charlesh88** [comment]
Testathon 031516
Per #445 thought I saw bad wait spinner in tree item when packets were loading.
