### ISSUE TITLE
[Edit Mode Prototype] Edit mode on objects that do not have a view supporting editing should edit properties instead.

### ISSUE THREAD

**Issue by akhenry** [nasa/openmctweb#320]
There was a regression in master which caused this functionality to change. This was fixed after NEM branch was taken, and merging from master subsequently has not fixed it in branch. Need to ensure that this functionality is enabled in NEM prototype.

**Comment by VWoeltjen** [comment]
> There was a regression in master which caused this functionality to change. 

This appears to be working correctly in master; perhaps I'm misunderstanding the issue description?

For reference, the rule implemented in EditActionPolicy (in `platform/commonUI/edit`) is that the Edit action should only be available for domain objects which have at least one view that supports editing. Otherwise, the Edit Properties action is available. (Applies only to the `view-control` category; the buttons on the top right.)

**Comment by akhenry** [comment]
Description could have been clearer :) Yep, the issue is fixed in master, but open199 was taken prior to fix. Due to code changes in open199 the fix needs to be applied slightly differently anyway. Was just noting the issue for my own reference.

Thanks for the clarification on the policy!

**Comment by akhenry** [comment]
Setting Milestone to Baxter. This is functionality that exists in master, so to have it absent from NEM prototype would be a regression.

**Comment by akhenry** [comment]
Hrm, I'm not sure that the behavior is actually working correctly in Master either -
1. Click on a telemetry panel, clock, timer, imagery, or web page from the navigation tree
2. Click on the edit icon
3. View goes into edit mode

My expectation here would be for the properties dialog to appear, not the edit mode view. For the above types, there is nothing that the user can do in edit mode, so it doesn't seem to make much sense to be in edit mode, and I suspect that this is not the intended behavior?

Clicking the edit icon for a folders, activities, or activity modes shows the properties dialog, which is the behavior that I would expect for the other object types listed above.

**Comment by akhenry** [comment]
Adding this to NEM Beta. Although it's not new behaviour (it's doing the same thing as Master) I suspect it's incorrect, and will quickly become apparently to users trying to edit objects.

**Comment by akhenry** [comment]
Believe that this is due to https://github.com/nasa/openmctweb/blob/master/platform/commonUI/edit/src/policies/EditActionPolicy.js#L48

Most of our view definitions do not specify editability, and the default is true, based on the above. As such, things like clocks, plots, scrolling views, etc will all go into edit mode when the edit button is clicked. This doesn't make any sense to me, because as far as I can tell, it's not actually possible to do any editing in these views?

@VWoeltjen is this the intended behavior? If not, I am going to modify these view definitions to set `editable: false` -

* clock
* timer
* scrolling
* plot
* page
* imagery

**Comment by VWoeltjen** [comment]
For clock, timer, page, imagery, don't see any plausible use for Editing.

For plot & scrolling, this is _possibly_ useful for a Telemetry Panel (e.g. if your goal during editing is to build up a particular multi-element plot.) But not useful for a Telemetry Point.

I see three options:

1. Just mark plot & scrolling as not editable and see if anyone misses them when editing a Telemetry Panel.
2. Leave plot & scrolling as-is; still see them in Edit mode for Telemetry Panel objects, and there shouldn't be an Edit mode for individual telemetry points (Sine Wave Generators notwithstanding)
3. Leave plot & scrolling as editable, but use a `view` policy to check whether they'd be available when editing. Would need to replace the `view.editable !== false` check with a `policyService.allow('view', view, new EditableDomainObject(domainObject)`, add a `view` policy which supports the normal `view.editable` check, and add a new `view` policy which handles the more nuanced logic for plot/scrolling...

Option 3 seems "most correct" to me but Option 1 and 2 are much more practical. Should check in with @charlesh88 about UX impact of Option 1 if we go that route.

**Comment by akhenry** [comment]
For NEM Beta I think __2__ is the best option. It's a little confusing to go into edit mode for a plot and seemingly not be able to do anything, but it's not the end of the world, and it is the current behavior in master.

**Comment by larkin** [comment]
You can actually go into edit mode on a plot and drag additional channels onto the plot, so seems to be some use for that as an intermediate stage that indicates "it's not saved yet".

**Comment by akhenry** [comment]
Created #404 to track later changes if we decide to do them. For NEM Beta the user will be able to go into edit mode on plots
