### ISSUE TITLE
Inspector open icon too subtle

### ISSUE THREAD

**Issue by RCarvalhoNASA** [nasa/openmctweb#335]
Testathon 20151123:  Compared to the other buttons up in its corner of the screen, the button to open the inspector (while it is closed) is far too subtle, and took a bit of searching for this user to find.

**Comment by larkin** [comment]
Closed with #691.

**Comment by Costigan** [comment]
The icon is now larger, but I don't think its meaning would be clear to a new user.  It's a different icon from the one on the left when the tree's pane is closed, so you can't transfer your knowledge from left to right.  The icon, a CBS eye, makes sense.  But you need to know a pane is over there before you'll associate the icons with opening that pane.
