### ISSUE TITLE
Bottom bar icon collapse too fast

### ISSUE THREAD

**Issue by RCarvalhoNASA** [nasa/openmctweb#336]
Testathon 20151123:  This is a bit nitpicky, but while browsing among the icons in the bottom bar, if one expands under my mouse, and then I try to move my mouse to expand the next one to the right, the item collapses so quickly that my mouse is over nothing at all.  It makes it a bit tricky to get a middle icon expanded.

**Comment by charlesh88** [comment]
@RCarvalhoNASA  I've experienced the same frustration. Think I've got an easy fix for this.

**Comment by charlesh88** [comment]
Fix for now pushed to open336; PR filed as #421.
