### ISSUE TITLE
[Style] In layout view, some frame controls shine through when frames overlap

### ISSUE THREAD

**Issue by akhenry** [nasa/openmctweb#341]
1. Create or edit a layout display such that its child objects overlap.
1. In browse + edit mode, the play/pause and open in new tab controls from the lower child shines through the upper child.
1. Additionally, in edit mode, if the lower child is selected, the resize indicator shines through

eg.

![layout frame controls](https://cloud.githubusercontent.com/assets/4215777/11354637/0d7e071a-9202-11e5-89a5-a6150cc4abb3.png)

**Comment by larkin** [comment]
I think this is a case where we use z-index to position these but they should use DOM ordering so that stacking is only relevant within each view's container.  Otherwise we would need to dynamically calculate z-index for not only each item in a layout, but the contents of those items.

**Comment by charlesh88** [comment]
Definitely a z-indexing issue - what's interesting is that it's only happening when the lower element is selected. I will take a look at this.

**Comment by charlesh88** [comment]
@akhenry Assume this was seen in open199?

**Comment by akhenry** [comment]
@charlesh88 seen and reported in master, also present in open199 (which is now defunct - use nem_prototype instead)

**Comment by charlesh88** [comment]
Work pushed to open341; PR filed as #418.
