### ISSUE TITLE
Minor issue when dropping packets into a layout being edited

### ISSUE THREAD

**Issue by Costigan** [nasa/openmctweb#380]
Create a layout.  Drag a packet into it.  The packet appears.  Good.
Drag another packet in.  The new packet also appears.  The previous packet is unchanged.  Good.
Drag the original packet in.  It doesn't appear.  Good.
Drag a third packet in.  It appears.  Good.
But the first packet now moves to the position where the second attempt to drop that packet occurred.  Bad (in a minor way)

**Comment by larkin** [comment]
Duplicated by #384, moving report to there.
