### ISSUE TITLE
Errors due to a loss of connection can't be displayed to the user.

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmctweb#383]
While testing #58, I disconnected my computer from the network to force a persistence error. I did receive the error in the status bar area, but once minimized, I couldn't cause the Messages overlay to appear by clicking the NOTIFICATIONS indicator element - probably because I was disconnected.

The Messages overlay should be able to be displayed when the user is disconnected. Or, we need another way to indicate to the user that the system is in a disconnected state. Assigning to Victor with the action to comment, or we can discuss options.

**Comment by VWoeltjen** [comment]
Think this is a good case for pre-fetching templates. Brute force solution would be to pre-fetch _all_ templates, or we could filter this down to templates with a `prefetch = true` property if that's too much of a hit on bandwidth on startup.

**Comment by larkin** [comment]
I think we go for a precompile step and precompile the templates so they all load at once.  But that's another question for platform/api discussions this week.

**Comment by VWoeltjen** [comment]
Agree, that's a better approach; will take more effort but will solve a broader range of latency problems.

**Comment by larkin** [comment]
Also just "makes sense" from the web app perspective. It's how it's done.

Pete

On Dec 7, 2015, at 4:52 PM, Victor Woeltjen <notifications@github.com<mailto:notifications@github.com>> wrote:


Agree, that's a better approach; will take more effort but will solve a broader range of latency problems.

**Comment by VWoeltjen** [comment]
Think this will be solved by solution to #58; giving same priority/assignment/etc

**Comment by VWoeltjen** [comment]
Resolved by #388
