### ISSUE TITLE
[New Edit Mode] Create menu in new edit mode

### ISSUE THREAD

**Issue by akhenry** [nasa/openmctweb#387]
Currently in NEM it is possible to launch the Create menu while editing. This will pull them out of new edit mode with no warning at the moment. Easiest solution for now is to disable create menu in new edit mode.

**Comment by charlesh88** [comment]
Assigning to myself; I will hide the Create button when it has a class of s-status-editing.

**Comment by akhenry** [comment]
Sounds good, thanks @charlesh88

**Comment by charlesh88** [comment]
Work done and pushed to open199f; pull request #393 created and assigned to Andrew - please close this issue if everything looks good.

**Comment by akhenry** [comment]
Looks good, closing.
