### ISSUE TITLE
[New Edit Mode] Drag-drop to initiate editing of timelines

### ISSUE THREAD

**Issue by akhenry** [nasa/openmctweb#395]
If in browse mode, dragging an activity onto a timeline will not add the activity to the timeline, nor initiate edit mode. 

If edit mode is initiated manually, then activities can be dropped into the timeline's swim-lanes.

@larkin Do we need this functionality for NEM Beta? If they don't use timelines, then I will de-scope for this beta release.

**Comment by charlesh88** [comment]
We've been showing Timelines to JPL, but only in the context of WARP. IMO, this should be de-scoped for this beta release.

**Comment by akhenry** [comment]
Ok, thanks for the info. Also there is a fairly simple workaround for this, which is to click the edit button, so it's not blocking functionality.

For these reasons, I'm going to descope for beta

**Comment by akhenry** [comment]
Closing. This feature was added some time ago.
