### ISSUE TITLE
[New Edit Mode] Selecting "Go To Original" from elements pool navigates without prompting user to save changes

### ISSUE THREAD

**Issue by akhenry** [nasa/openmctweb#396]
In New Edit Mode, if editing a dirty object, the user is able to select "go to original" from the context menu on an object in the elements pool. The user is then immediately navigated to the original object without prompting to save, leaving the object being edited in a dirty state.

**Comment by VWoeltjen** [comment]
It's a little hacky, but edit mode could listen to `navigationService` for changes. If there are unsaved changes, you could prompt the user and `navigationService.setNavigation` back to the object being edited. Would have the nice side-benefit of intercepting navigation changes initiated in other ways.

**Comment by akhenry** [comment]
Believe this is fixed by https://github.com/nasa/openmctweb/commit/2ca414d2a40216a5ef1222e5daf22cbbc09225a8
