### ISSUE TITLE
[Edit] Drag from tree to elements pool not supported

### ISSUE THREAD

**Issue by larkin** [nasa/openmctweb#419]
Dragging and dropping an object from the search results or regular tree to the element pool in new edit mode does not add the object to the elements pool as it would in old edit mode.  For views that do not support standard drag and drop composition, it is impossible to add objects to them.

**Comment by akhenry** [comment]
This should be easy enough to add, before I do I'd like to better understand this statement -

    For views that do not support standard drag and drop composition, it is impossible to add objects to them

Which views in particular are you thinking of? I'd like it if any objects that support composition also  supported drag-drop into the view itself.

**Comment by akhenry** [comment]
Hrm, I hate to be the guy who says "It works for me", but it works for me. Are you seeing this in open?

**Comment by larkin** [comment]
That's an ideal goal but it hasn't always been true.  panel plots didn't support it initially.  Some vista views don't have it enabled.  Perhaps we consider adding it to those views a requirement before we deploy NEM? That's the direction we're going, anyways.

If you take one of the current views and remove the drop gesture from the definition, does dropping into the elements panel still work?

**Comment by akhenry** [comment]
Ok, so I took the layout view and disable the drop gesture in its definition. Drop into the elements pool still works. In the process of doing this I did find another bug though, which I'm just about to ticket.

**Comment by charlesh88** [comment]
This is feeling a lot like feature creep to me. Also, I'm not a fan of dragging to the elements pool in NEM - the goal is to support directly dragging onto the view area. It might make sense to allow a drop into both areas. 

What I'm really NOT a fan of is drop only into the elements pool with no support for dropping in the work area. This has proven to be very confusing to users, as for some views you can directly drop and others you can't.

**Comment by larkin** [comment]
Ok.  I'm happy with that.  It's been confusing in the past and it's confusing in the future, so let's strike this out.

It also may have been a NEM integration bug; I'm closing it for now.
