### ISSUE TITLE
[Edit Mode] Drag-drop onto plot within a layout triggers the unsaved changes prompt

### ISSUE THREAD

**Issue by akhenry** [nasa/openmctweb#423]
1. Take a layout that is in browse mode and which contains a plot. 
2. Drop another plot on top of that plot.
3. User is warned about navigating away with unsaved changes. Hitting cancel does not work.

**Comment by charlesh88** [comment]
It's probably obvious, but the behavior we want (until we get to sub-object editing) is for the layout to get the drop gesture, not the sub-object. When get we get to SOE, we probably want the drop to go into the sub-object, but with the layout as the outer object being edited.

**Comment by akhenry** [comment]
Ok, think I've fixed this. Event capture mode is bubble by default and both plots and layouts were accepting drops. Longer term this is what we will want for SOE, but for now I've removed the drop gesture from plots and layouts and put it on the browse-object view which contains them.
