### ISSUE TITLE
[CSS] Splitter is blocking mouse events when treeview is collapsed

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmctweb#426]
[Testathon 20151214] First seen by Robert during Testathon 12-14-15. When the treeview is collapsed, the splitter bar's opacity is set to 0, but it still remains to grab mouse events like hover, allowing it to block elements underneath it from responding to clicks or hovers. 

The fix: set the splitter to have point-events: none when it's in that mode. Make sure to do this for all splitters generically.

**Comment by VWoeltjen** [comment]
Marked as critical because it can prevent access to data

**Comment by charlesh88** [comment]
Work pushed to open426; PR filed as #432.

**Comment by RCarvalhoNASA** [comment]
20151217 Testathon This is now inconsistent, some pages it is showing up on and others it is not, but where it shows up, it is still interfering.  Driving Plots Layout

**Comment by charlesh88** [comment]
20151217 Testathon 
Fix wasn't actually integrated when Robert was testing; we got it merged in and I can confirm this is now fixed.
