### ISSUE TITLE
Panels don't begin updating Plot view initially

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmctweb#429]
[Testathon 20151214] First seen by Robert during Testathon 12-14-15. When a Layout or a Panel is opened in a new tab via a context menu, the "Open in a new browser tab" button at upper right, or even just navigating directly to the URL in the browser for that object, the plot view for any Panels (either when viewing the Panel directly, or Panels embedded in a Layout) don't render both X and Y tick labels and don't begin plotting data. Switching the Panel to Scrolling view and back to Plot view will cause the plot to begin updating properly.

**Comment by akhenry** [comment]
I also experience this issue, but it was not limited to new tabs. I am also seeing it the first time I visit a layout with plots. If I navigate away and come back, the plot starts showing data.

Steps to reproduce:
1. Open a fresh WARP session 
2. Navigate to My Items > RP15 Layouts > Location Layout
3. Location Quaternion Panel and Location Vector Panel do not show any data
4. Navigate to Driving Plots Layout. Also does not show data in Wheel Steer, Wheel Susp, and Drive state panels
5. Navigate back to Location Layout. All plots display data.

**Comment by charlesh88** [comment]
Confirmed behavior as Andrew describes, modifying title of issue accordingly.

**Comment by VWoeltjen** [comment]
Think this might be related to loading strategy for the relevant points; they start in a pending state, then have information populated from dictionary. If plot does not detect this change then subscription may not be correctly formed.

Latency of ES might be relevant here too

**Comment by VWoeltjen** [comment]
"Pending" objects do appear to cause this; can reproduce regularly with a panel containing several points, or links to individual points. If I remove the "pending" behavior and just defer providing objects until they're ready to be used, this behavior disappears. But, has a negative impact on user experience (various parts of the application get stuck waiting for these to fully load.)

Will look at alternatives, such as listening to mutation on domain objects and refreshing subscriptions when it occurs.

**Comment by VWoeltjen** [comment]
Filed https://trunk.arc.nasa.gov/jira/browse/WTD-1620 for review and integration

**Comment by VWoeltjen** [comment]
Changes referenced above have been integrated

**Comment by RCarvalhoNASA** [comment]
20151217 Testathon looks good now, thanks!

**Comment by charlesh88** [comment]
20151217 Testathon verified as fixed.
