### ISSUE TITLE
[Build] Choose packaging system

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#458]
Trade study to select a packaging system, focused on being easily consumed by dependent projects.

From [refactoring plan](https://github.com/nasa/openmctweb/blob/api-redesign/docs/src/design/planning/APIRefactor.md#step-2-incorporate-a-build-step):

> Should also consider which dependency/packaging manager should
be used by dependent projects to obtain Open MCT Web. Approaches
include:

> 1. Plain `npm`. Dependents then declare their dependency with
   `npm` and utilize built sources and assets in a documented
   fashion. (Note that there are
   [documented challenges](http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging)
   in using `npm` in this fashion.)
> 2. Build with `npm`, but recommend dependents install using
   `bower`, as this is intended for front-end development. This may
   require checking in built products, however, which
   we wish to avoid (this could be solved by maintaining
   a separate repository for built products.)

**Comment by VWoeltjen** [comment]
SystemJS should also be considered here

**Comment by VWoeltjen** [comment]
Some background in WTD-1159

**Comment by VWoeltjen** [comment]
Given the candidates (`bower` and `npm`), think that `npm` is the logical option due to the following limitations/concerns:

* `bower` requires built sources to be checked in; we generally want to avoid this (creates redundancy in the repository, can trigger meaningless merge conflicts, etc.) We've done this for generated CSS and experienced pain as a consequence; this seems like going in the wrong direction.
  * `npm`, on the other hand, includes `prepublish` and `postinstall` hooks, such that builds can be triggered as part of the installation process.
* Value-added of `bower` is, more-or-less, the ability to declare a dependency and download the relevant artifacts to a known location. `npm` provides same basic functionality.

As such, prefer using `npm` in this context. Note that this does not prevent us from, say, hosting built artifacts (perhaps in a `bower`-friendly repository) in the future.

Proposed usage is to build all artifacts necessary to run an instance of Open MCT Web in a `dist` folder. Ensure this gets populated on `prepublish`. This would include, at minimum, a minified `openmctweb.js`, one or more CSS files, and other assets such as images in a hierarchy of our choosing.

Users would then be able to:
* Simply load MCT via a script tag in their HTML document (e.g. `<script src="node_modules/openmctweb/dist/openmctweb.js" ...`)
* Depend on Open MCT Web from a CommonJS module (e.g. `require('openmctweb')`), and proceed to Browserify that (or do any number of other things with that) 
* Write plugins as UMD modules that detect an `openmctweb` global and install to that, _or_ that `define` a dependency on `openmctweb`, _or_ that `require('openmctweb)`

Note that Open MCT Web would need to provide a means to pass in a path to its assets, to allow for some flexibility in the directory structure of its deployment. Think it is fine to default this to `node_modules/openmctweb/dist/assets` (e.g. to assume it will be used in-place)

**Comment by VWoeltjen** [comment]
@larkin / @akhenry - in lieu of writing up a trade study and filing a PR (as I'd originally proposed), think it's easier to handle this in the comment thread here (we still get the record of the decision that we want.)

Thoughts on proposed decision/rationale above? :+1: :-1:?

**Comment by akhenry** [comment]
As an aside, may want to commit some build artifacts, eg. tagged, minified, stable releases for public consumption. But that's besides the point, and is a whole other discussion.

I'd certainly prefer SASS compilation to be part of our build process. 

I think that npm makes sense. It's infinitely scriptable. I've only ever used bower for managing external third-party dependencies, where build artifacts are hosted in a CDN, github repo, etc., not as a means of managing intra-project dependencies. For the latter my experience is limited to Maven and Nexus, which are not appropriate in this situation.

Did you consider Grunt, Gulp etc? They're more oriented toward the build workflow than npm and probably have solutions to common use cases like this. In any case, using Maven going forward doesn't make a lot of sense, we should use a more js oriented build environment.

**Comment by VWoeltjen** [comment]
> As an aside, may want to commit some build artifacts, eg. tagged, minified, stable releases for public consumption. But that's besides the point, and is a whole other discussion.

Do think we should provide built artifacts, but would like to use `npm publish` for this (at least, for Open MCT Web and any open source plugins)

> Did you consider Grunt, Gulp etc? They're more oriented toward the build workflow than npm and probably have solutions to common use cases like this. In any case, using Maven going forward doesn't make a lot of sense, we should use a more js oriented build environment.

Yep, #459. (Issues are a little poorly-titled; the intent of this issue is really "how will others use our artifacts", whereas #459 addresses "how do we produce our artifacts")

**Comment by akhenry** [comment]
Ah, my apologies, I've conflated the two issues.

**Comment by akhenry** [comment]
> Do think we should provide built artifacts, but would like to use npm publish for this (at least, for Open MCT Web and any open source plugins)

Makes sense

**Comment by larkin** [comment]
I prefer npm over bower, bower is really intended to be for front end javascript libraries, and while we are mostly a front end, we blur the line from time to time with our dev server.  Plus, bower has always felt a little more buggy to me.

Not sure that we want to publish openmctweb to npm; it seems fine to use the public git url (other packages depending on openmctweb would specify the dependency using a git url.  But that's not part of this discussion.

**Comment by VWoeltjen** [comment]
> Not sure that we want to publish openmctweb to npm; it seems fine to use the public git url (other packages depending on openmctweb would specify the dependency using a git url. But that's not part of this discussion.

Agree, using the git URL is sufficient for all of our immediate needs.

Think we have reasonable consensus here, I will go ahead and mark this resolved.
