### ISSUE TITLE
[Build] Choose build system

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#459]
Trady study to choose a build system for Open MCT Web.

From [refactoring plan](https://github.com/nasa/openmctweb/blob/api-redesign/docs/src/design/planning/APIRefactor.md#step-2-incorporate-a-build-step):

> Some goals for this build step:

> * Compile (and, preferably, optimize/minify) Open MCT Web
  sources into a single `.js` file.
>  * It is desirable to do the same for HTML sources, but
    may wish to defer this until a subsequent refactoring
    step if appropriate.
> * Provide non-code assets in a format that can be reused by
  derivative projects in a straightforward fashion.

...

> In all cases, there is a related question of which build system
to use for asset generation/management and compilation/minification/etc.

> 1. [`webpack`](https://webpack.github.io/)
   is well-suited in principle, as it is specifically
   designed for modules with non-JS dependencies. However,
   there may be limitations and/or undesired behavior here
   (for instance, CSS dependencies get in-lined as style tags,
   removing our ability to control ordering) so it may
> 2. `gulp` or `grunt`. Commonplace, but both still require
   non-trivial coding and/or configuration in order to produce
   appropriate build artifacts.
> 3. [Just `npm`](http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/).
   Reduces the amount of tooling being used, but may introduce
   some complexity (e.g. custom scripts) to the build process,
   and may reduce portability.

Note that most options include some more complexity than this. Need to review open issues related to build process to understand requirements here.

Should also consider use of SystemJS in this context (from #263)

**Comment by VWoeltjen** [comment]
Closely related to #458

**Comment by VWoeltjen** [comment]
Some specific tasks we want in the build, along with general observations:

1. Don't normally want to write/maintain a lot of custom build-related scripts. (Put another way, want to be able to describe build steps at the highest level of abstraction feasible.)
2. Do want to have the flexibility to be able to write custom build steps in exceptional circumstances. (Sometimes what you really want just isn't out there.) 
3. As part of the build process, want to:
  1. Run tests (unit tests and functional tests)
  2. Capture code coverage information.
  3. Minify JavaScript sources into a single artifact (or small number of artifacts)
  4. Compile SASS->CSS, locate within an `assets` hierarchy
  5. Compile templates into a single artifact (probably same JS artifact above)
  6. Produce documentation (both JSDoc, and from Markdown sources)
  7. Enforce code style (JSHint)

Evaluating options from above:

* Would like to rule out "Just `npm`" quickly. We've been using this for a few tasks and are already experiencing some of the drawbacks of doing things this way. In general, it drives you toward writing _ad hoc_ build scripts, like our documentation generator. Additionally, getting such a build to work cross-platform is tricky at best, and a number of common behaviors typically allocated to JS build tools (e.g. watches) are also made harder than they need to be by pushing `npm` to this degree.
* `webpack` doesn't really belong in the comparison above. Really, the trade there should be among `webpack`, `r.js`, and `browserify` (bundling tools.) Given existing usage of RequireJS, think `r.js` is the presumptive choice there (`browserify` requires plugins for compatibility with AMD; `webpack` offers additional power but is monolithic, don't see immediate downside to managing non-JS artifacts with separate tools.)

This leaves `gulp` and `grunt`. This is a comparison that has been made several times before; synthesizing information from [various articles and blog posts](https://www.google.com/search?q=gulp+vs+grunt):

* Gulp is more efficient due to a stream-based approach (prefer passing data around in-memory than on-disk.)
  * This efficiency difference will probably not matter for us (and Grunt is moving toward stream support anyway.) Our code base is not huge.
* Gulp favors code; Grunt favors configuration.
  * Gulp gets a small win here as it is much in line with our "don't want to write our own scripts for common things, do want to be able to write our own scripts for uncommon things." (Certainly possible with Grunt too but much easier in Gulp)
* Grunt has been around longer and has more plugins.
  * The set of tasks we want to do are rather unexceptional, so expect both task runners to have all the plugins we need.

As such, think our build system should be Gulp, with specific build tasks handled as follows:

  1. `karma` to run tests (unit tests and functional tests)
  2. `istanbul` (via `karma-coverage`) to capture code coverage information.
  3. `r.js` (RequireJS optimizer) to minify JavaScript sources into a single artifact (or small number of artifacts)
  4. `compass` (via `gulp-compass`) to compile SASS->CSS and output within an `assets` hierarchy
  5. `text` plugin for RequireJS to compile templates into a single artifact
  6. #225 to produce documentation (both JSDoc, and from Markdown sources)
  7. `jshint` to enforce code style

**Comment by VWoeltjen** [comment]
@larkin / @akhenry - thoughts on the build as described above?

**Comment by larkin** [comment]
+1 Gulp.

Definitely down for replacing `jslint` with `jshint`.  May even want to use `eslint`, which is a much more configurable option.  I would consider both of these as "code correctness" tools and not "code style" tools.

Code style:  `jscs` seems like an easy pick here, allows us to codify all of our code style rules separate from code correctness.

Otherwise good.

**Comment by akhenry** [comment]
It sounds sensible to me. Don't have experience with Gulp. Some experience with Grunt, which was very configuration heavy and not super intuitive to modify.

jshint is a good choice.

+1 for integrating compass with the build process. Is the intention here to remove the generated CSS from the repo in that case?

**Comment by larkin** [comment]
> +1 for integrating compass with the build process. Is the intention here to remove the generated CSS from the repo in that case?

I think so-- generally remove all built files from the repo.  At some level, it would be nice to store built artifacts though-- we might want to change the gh-pages build process to stop throwing away history.  Would give us a branch that we can track historical builds of the tool and the docs.

**Comment by VWoeltjen** [comment]
>  Definitely down for replacing `jslint` with `jshint`.  May even want to use `eslint`, which is a much more configurable option.  I would consider both of these as "code correctness" tools and not "code style" tools.

> Code style:  `jscs` seems like an easy pick here, allows us to codify all of our code style rules separate from code correctness.

Good points/suggestions, I've amended the description above for these.

> +1 for integrating compass with the build process. Is the intention here to remove the generated CSS from the repo in that case?

Yes; added a comment to #238 reflecting this, but I think we should address this during build changes associated with API Refactor.
