### ISSUE TITLE
[New Edit Mode] Creating an Activity within timeline causes navigation to the new activity

### ISSUE THREAD

**Issue by akhenry** [nasa/openmctweb#480]
1. In new edit mode, open a timeline. 
2. Create a new activity by clicking on the Add button.
3. Enter activity details and click OK
4. User is navigated to the new activity. Desired behavior is to remain on the Timeline screen. This is currently masking the behavior described in #305

**Comment by VWoeltjen** [comment]
@akhenry - this is addressed by #500, correct? (Can this be closed?)

**Comment by akhenry** [comment]
@VWoeltjen correct, closing

**Comment by RCarvalhoNASA** [comment]
Verified as fixed Testathon 20160209
