### ISSUE TITLE
Itemize NEM Edit Mode Refactors

### ISSUE THREAD

**Issue by larkin** [nasa/openmctweb#481]
From [Victor's comment](https://github.com/nasa/openmctweb/pull/474#issuecomment-171807999)

> Apologies for not commenting in here sooner; the things I'd like to see accounted for in follow-up issues are, generally:
> 
> * Refactoring out NEM-related changes from other bundles
> * Restoring test cases which have been xit'd out in the context of this PR (which I think should be done after refactoring out NEM changes)

> My intent had been to go through and review and itemize these, but haven't found the time to do so; at this point I'd be fine with just one or two catch-all issues filed in Clarke which basically just reiterate the above.

**Comment by larkin** [comment]
Not sure if this should be @VWoeltjen or @akhenry?

**Comment by VWoeltjen** [comment]
Specific tasks (will file follow up issues for these):

* Remove edit-related concerns from Browse controllers
  * Specifically, BrowseController and BrowseObjectController. 
  * Ideally, removing the "edit" bundle and leaving the "browse" bundle in place should mean that browsing just works, but that editing is no longer an option
  * Does not necessarily mean these need to be identical to their pre-NEM state, just that NEM-specific concerns should not have a home there. Completely valid to introduce new hooks or extension points to Browse to facilitate NEM, so long as those are logically within the scope of Browse responsibilities.
* Remove Edit mode workflow from Create action
  * Again, should be able to remove "edit" as a bundle and still be able to Create things.
  * Some approaches here - decoration, substitution (most/much creation-related code is already delegated to the CreationService, so an alternate Create action might be able to use that without redundant code). Solving #546 might open the door for a more cleanly-separated solution here.
  * Solution to #491 may be helpful here (or may do this already)
* Restore or rewrite `x`'d out tests
  * See #474 (should be easy to find usages of `xdescribe`, `xit`)
  * In cases where tested functionality is truly obsolete, just remove these
* Simplify SaveAction
  * The number of dependencies and the number of LOC here both indicate that this action has many responsibilities. Its responsibility should be simple - "persist any changes made during editing" - and any workflow-related behavior should be separated into other classes. (_Or_, say that the "Save" action is narrowly responsible defines this specific workflow, and have it act as a manager for other classes which implement the various parts of that workflow.)
* Remove Edit-related concerns from Action capability
  * Should handle this with a decorator, or policy, or something along those lines.
* Refactor ConductorRepresenter to be less sensitive to specific details of DOM
  * This was really an existing flaw of that representer. Think this should be easier after the API Refactor, particularly once we have a better set of interfaces for dealing with UI components
* Remove Editing workflow concerns from FixedController, LayoutController
  * Specifically, the `setEditable` calls on drop
  * Want to minimize the degree to which individual view types need to know about Edit mode.
* Remove Edit-related concerns from mct-representation
  * Should actually be low priority, may want to remove mct-representation during API refactor
* Remove Edit-related concerns from ContextMenuGesture
  * Menu should be suppressed in these cases, but responsibility for this suppressing should be externalized.
* Remove Edit-related concerns from DropGesture
  * Triggering of related workflow behavior (e.g. starting editing, creating virtual panels) should be a responsibility of components in the Edit bundle

**Comment by akhenry** [comment]
This is great, thanks for doing this Victor
