### ISSUE TITLE
Duplicate calls create object twice with same id

### ISSUE THREAD

**Issue by larkin** [nasa/openmctweb#497]
Reported by @charlesh88 in https://github.jpl.nasa.gov/MissionControl/vista/issues/264.  
Expected behavior: duplicate duplicates an object
Actual behavior: duplicate fails to duplicate an object.

Problem analysis: Duplicate calls the createObject method two times with the same id.  For persistence providers that prevent creating objects which already exist, this fails, which causes the duplicate operation to fail.

In the open branch, I added logging to the persistence aggregator and duplicated an object that contains two objects.  The resulting log entries look like:

![screen shot 2016-01-21 at 11 34 09 am](https://cloud.githubusercontent.com/assets/226503/12492023/02434658-c033-11e5-890c-0f9e1a45d07e.png)

The duplicate action should not attempt to create the same object twice.  If the second call is necessary, it should be an update.

Sending to @akhenry, please reassign if not correct.

**Comment by akhenry** [comment]
I don't understand the commit history here, but this fix appears to have been merged into Master, so I'm closing this issue.
