### ISSUE TITLE
[Plot] Add plot markers and toggle

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#551]
<p>Add a toggle to show/hide markers on a plot, as shown in UI docs attached to <a href="https://trunk.arc.nasa.gov/jira/browse/WTD-868" title="UI for setting plot bounds in a plot view" class="issue-link" data-issue-key="WTD-868"><del>WTD-868</del></a>, p 71 bullet 6 and p 76</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1140
Originally created: Sun, 26 Apr 2015 11:08:28 -0700
Updated: Thu, 14 Jan 2016 16:31:56 -0800

**Comment by charlesh88** [comment]
Design has changed somewhat, closing this as out-of-date. Related to #580.
