### ISSUE TITLE
Fix loading spinner in treeview

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#554]
<p>Loading spinner in the treeview is now the wrong size. Fix it.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1323
Originally created: Mon, 22 Jun 2015 18:45:46 -0700
Updated: Thu, 7 Jan 2016 16:25:40 -0800

**Comment by charlesh88** [comment]
Size is good, but Linux still unhappy. Closing this one.
