### ISSUE TITLE
selecting an option in create menu sometimes results in no object being created

### ISSUE THREAD

**Issue by larkin** [nasa/openmctweb#60]
When using the create menu, I am surprised to find that clicking to create an object sometimes dismisses the menu instead of opening the new object dialog box.  The actual ng-click is attached to the text, but the hover effect and cursor shows a much larger click target.

This screenshot explains the current functionality:
![create menu sensitivity](https://cloud.githubusercontent.com/assets/226503/9099462/b74a59a2-3b85-11e5-873d-ef5adc248dff.png)

This screenshot shows the expected functionality:
![expected](https://cloud.githubusercontent.com/assets/226503/9099464/bd796606-3b85-11e5-84c1-68f8b858e38d.png)

this bug is a demokiller.

**Comment by VWoeltjen** [comment]
@charlesh88 - is this another case where we can solve with markup/css tweaks? Maybe just need to move the `ng-click` to the correct element

**Comment by larkin** [comment]
this is definitely a quick fix; moving ng-click would be fine.

**Comment by VWoeltjen** [comment]
Verified during testathon 9/17/2015
