### ISSUE TITLE
Generic Export Service to allow csv exports

### ISSUE THREAD

**Issue by larkin** [nasa/openmctweb#649]
Discussing requirements for various exports-- it would be great to have a generic csv export service available to developers.  Would be connected to various export tools.

possible interface:
```javascript
/**
 * Generate a CSV and prompt the user to save as file.  
 * @param {Array[]} rows - arrays of row values
 */
exportService.exportCSV(rows);
```

alternatives
```javascript
/**
 * Generate a CSV and prompt the user to save as file.
 * @param {Array} headers an array of headers for the csv
 * @param {Object[]} rows row data, only keys in `headers` are used in csv
 */
exportService.exportCSV(headers, rows);
```

This service can then be wired up to various views and objects via actions or controllers and provide csv export functionality.  

There are probably third party libraries which would make implementation of this trivial.

@VWoeltjen what are your thoughts on implementation here?  We'd need something available for various R2 requirements.

**Comment by VWoeltjen** [comment]
This would be fairly straightforward to implement, but I have a couple of concerns with doing this in browser:

* How do we make the resulting file available for download? I've done this in the past with data URIs, but the problem you run into is that there is a maximum length (which varies from browser to browser, version to version, and can't be reliably determined at run-time). In Chrome this is 2MB (that number may be out of date) and for things like telemetry queries it is very easy to exceed that.
  * It looks like [blob URIs](https://developer.mozilla.org/en-US/docs/Web/API/Blob#Example_for_creating_a_URL_to_a_typed_array_using_a_blob) are the better approach here; haven't used these so not sure if we'll run into similar (or different) limitations.
* Even if we get past the 2MB limit, at some point (for telemetry queries) we'll hit a size limit where it just doesn't make sense to be doing this in-browser (would be nicer to handle with a streaming approach server-side.)

That said, I think we need to handle this in-browser for at least one case (timelines) so it makes sense to make it available for other uses. It will probably be simplest to use this for telemetry as well and move to a server-side solution if/when we start hitting size limitations in practice.

**Comment by larkin** [comment]
@VWoeltjen there's some W3C apis for it, from https://github.com/eligrey/FileSaver.js/:

| Browser        | Constructs as | Filenames    | Max Blob Size | Dependencies |
| -------------- | ------------- | ------------ | ------------- | ------------ |
| Firefox 20+    | Blob          | Yes          | 800 MiB       | None         |
| Firefox < 20   | data: URI     | No           | n/a           | [Blob.js](https://github.com/eligrey/Blob.js) |
| Chrome         | Blob          | Yes          | [500 MiB][3]  | None         |
| Chrome for Android | Blob      | Yes          | [500 MiB][3]  | None         |
| IE 10+         | Blob          | Yes          | 600 MiB       | None         |
| Opera 15+      | Blob          | Yes          | 500 MiB       | None         |
| Opera < 15     | data: URI     | No           | n/a           | [Blob.js](https://github.com/eligrey/Blob.js) |
| Safari 6.1+*   | Blob          | No           | ?             | None         |
| Safari < 6     | data: URI     | No           | n/a           | [Blob.js](https://github.com/eligrey/Blob.js) |

**Comment by larkin** [comment]
Agree that simple practice is generate CSVs and save; there is some level at which it will have to be implemented server side but we'll get there when we get there.
