### ISSUE TITLE
[New Edit Mode] Timeline edit restrictions

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#659]
From @RCarvalhoNASA:

> New edit mode for timelines seems to have lost the ability to resequence activities within a timeline.  I think I used to be able to drag items up and down the list, put them inside or pull them outside of each other, but now I don't seem to be able to do that anymore.  At a minimum, the dialog to create a new activity while editing inside a timeline should include the locator option, to make sure I agree I'm putting the new activity inside the currently selected activity/timeline so that I can manipulate the hierarchy as I'd like.  Right now I can't correct the subactivity layering without deleting and recreating.

**Comment by charlesh88** [comment]
Confirmed by Charles: dragging swimlane labels is no longer enabled, but should be. Hover effect is also not present.

**Comment by akhenry** [comment]
Ah, found the problem.

@charlesh88 I could use your css-fu for this one.

The activity in the timeline is represented by an `<mct-representation key='label'..` ([here](https://github.com/nasa/openmctweb/blob/master/platform/features/timeline/res/templates/tabular-swimlane-cols-tree.html#L51)). For whatever reason, this is a non-visible element in NEM, but was visible (ie. had size, and could be selected) in old edit mode. This has no obvious consequences at first glance as the HTML inside of it is visible. Unfortunately the drag events are attached to the mct-representation element itself, so it needs to be present for drag to work.

The element has height and width, and the z-index is ok, so the problem appears to be related to its inherited `display`. Manually setting the element to `display: block;` fixed it - the element could now receive drag events. Adding the class 'abs' to the `mct-representation` element it also worked, but this might not be desirable as it sets it to absolute positioning.  Could be flex layout related?

**Comment by charlesh88** [comment]
Taking a look now.

**Comment by charlesh88** [comment]
@akhenry @VWoeltjen Question about a fix for this: what branch should I look at to start working on this (warp-master?) and what branch should I do the fix in (master?)

**Comment by akhenry** [comment]
@charlesh88 A new branch based on open master

**Comment by charlesh88** [comment]
@akhenry Thanks!

**Comment by akhenry** [comment]
@charlesh88 Thanks for looking into it!

**Comment by charlesh88** [comment]
@akhenry Can we do a Hangout on this? Have some stuff re. draggable I want to work out.

**Comment by akhenry** [comment]
Ok, so enabling draggability in timelines revealed some odd behaviour. As per discussion with Charles
1. A child activity of another activity could be dragged into the parent timeline causing two instances of that activity to appear in the timeline
2. Dragging a timeline onto itself caused an infinite recursion, crashing the browser.

I have pushed a fix for both of these issues, with some discussion in ____

**Comment by akhenry** [comment]
Believe that this issue is now resolved with #667 and #668. Scope did end up creeping a bit and some issues (comment above) that were not originally reported were fixed along the way. The severity of the newly revealed issues and the relative triviality of the fixes I think justified the scope creep.

**Comment by RCarvalhoNASA** [comment]
Testathon 20160211 While this does appear to work functionally now, dragging a subactivity out from under its parent appears to create a link to the subactivity in the new location(s).  The item's location is still (according to the inspector panel) in the original parent activity, though it does not appear there in either the tree view or the timeline view.

**Comment by RCarvalhoNASA** [comment]
Not being a github expert, I'd like to figure out a way to split the following text out of the original report of this bug to become an independent feature request:
At a minimum, the dialog to create a new activity while editing inside a timeline should include the locator option, to make sure I agree I'm putting the new activity inside the currently selected activity/timeline so that I can manipulate the hierarchy as I'd like.

**Comment by VWoeltjen** [comment]
> Not being a github expert, I'd like to figure out a way to split the following text out of the original report of this bug to become an independent feature request:

Filed #674 for this, added a few notes on this. We used to support this, so I labelled this a regression (as opposed to a feature request)

As far as using GitHub, I just used New Issue and copy-pasted, then formatted with [Markdown](https://guides.github.com/features/mastering-markdown/).

**Comment by akhenry** [comment]
Testathon 20160211

Verified as fixed. Great work!

**Comment by akhenry** [comment]
@akhenry Thanks!
