### ISSUE TITLE
When looking at RP15 Timeline Rev A, info bubble sometimes points at the wrong place

### ISSUE THREAD

**Issue by Costigan** [nasa/openmctweb#716]
The bottom 3 rows have this problem

**Comment by charlesh88** [comment]
![testathon 03032016 hover bubble offset problem](https://cloud.githubusercontent.com/assets/1056412/13513389/66a67e7e-e155-11e5-8468-e94a65ce3e74.png)

**Comment by VWoeltjen** [comment]
This is especially visible for objects in the bottom right (bubble is positioned as if arrow should be in bottom-right corner, but arrow remains in top-left)

**Comment by VWoeltjen** [comment]
Well, that's silly. [This line](https://github.com/nasa/openmctweb/blob/master/platform/commonUI/inspect/src/services/InfoService.js#L88), introduced in 73dc16d398b134943392abffbe60aeb45964513f, is clearly the source of the problem: Appropriate classes are computed and then promptly overwritten.
