### ISSUE TITLE
Allow treeview to be collapsed

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmctweb#72]
Allow the user to collapse and hide the treeview in 'browse' mode. See pgs. 19 - 21 in UI sketches v2.1, https://drive.google.com/a/nasa.gov/file/d/0B0v27OM1JkSeR001RFJZMk43QVk/view?usp=sharing.

- A button will need to be added to the splitter bar (when visible) to effect the collapse.
- Buttons available when the treeview is hidden will allow expansion of the treeview, and access to the Create menu.
- The treeview should be hidden by default when opening an object in a new browser tab. This means that we may want to allow a querystring param in the URL to control the visible state of the treeview as well as an ng-click when navigating within a single window.

**Comment by slhale** [comment]
I've gotten all the main things done now. I think all that's left is the styling. @charlesh88, you wanted to do that right?

**Comment by RCarvalhoNASA** [comment]
Testathon 20151123:  Verified this is working now
