### ISSUE TITLE
Object Inspector

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmctweb#73]
Allow information to be displayed about objects via an Inspection panel. See pgs. 23 - 26 in UI sketches v2.1, https://drive.google.com/a/nasa.gov/file/d/0B0v27OM1JkSeR001RFJZMk43QVk/view?usp=sharing.
- This pane will need to operate in the same was as the treeview, allowing the user to resize and collapse it. See #72.
- Selectable objects should include tree items, and sub-element items during editing such as the legend of a Telemetry Point in a Panel's plot view, clicking a Telemetry Point in a Panel's Fixed Position view, or clicking a frame while editing a Display Layout.
- This element should be architected as much as possible to support multiple item selection, particularly in Timelines.

**Comment by RCarvalhoNASA** [comment]
Testathon 20151123:  Inspector appears as expected
