### ISSUE TITLE
[Platform] Graceful failover when `persistenceService` is not provided

### ISSUE THREAD

**Issue by danielpacak** [nasa/openmctweb#79]
By default the maven build excludes the example folder that provides the `persistenceService`. Therefore the app fails but I have no clue what happens untill I open the JavaScript console in my web browser.

![mct_failover_message](https://cloud.githubusercontent.com/assets/1322923/9378198/d5720f06-471f-11e5-9ccf-32d84f955224.png)

**Comment by VWoeltjen** [comment]
Thanks for reporting this - this is a big omission 

I think there's two different sub-issues here:

1. There's no platform implementation of a persistence service that can be used to run "out of the box." 
2. When there is no provider available for a composite service that is used by some loaded bundle, the application fails to load.

For (1), I'd like to move `example/localStorage` into platform, and add with a status indicator saying "Local storage" with a tooltip indicating that changes are being stored in-browser and won't be available from other devices or other browsers.

For (2), I think that is more of an architectural issue. A missing dependency causing an unrecoverable failure seems okay to me, and the developer console is an appropriate place to display that warning. What I don't like is that we don't have a way to define more graceful failure mechanisms on a service-by-service basis (in the case of persistence, you could recover by warning the user that they won't be able to save anything.) Adding a proposal to address this as part of our [API redesign](https://github.com/nasa/openmctweb/blob/api-redesign/docs/src/design/proposals/APIRedesign.md#allow-composite-services-to-fail-gracefully)

**Comment by danielpacak** [comment]
Makes sense for me. BTW, I've recently faced a similar problem for persisting interconnected data in a web browser for demo/selling purpose and I ended up with this "crazy?" idea: https://github.com/SOFTWARE-CLINIC/sc-embedded-database.
