### ISSUE TITLE
[Plot] Dates show 1970 when there is no data

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#80]
When viewing a plot with no data, time axis shows various times in 1970.

Axis labels should instead be empty (?) or at least at some reasonable defaults.

**Comment by akhenry** [comment]
Closing this issue, was resolved by https://github.com/nasa/openmctweb/pull/168

**Comment by RCarvalhoNASA** [comment]
Testathon 20151123:  Verified this is OK now
