### ISSUE TITLE
Show Context Menu from "items" view

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#9]
Show context menu from individual "grid items" in a view of a folder (the only view of a folder, currently.) User should be able to right-click on a domain object within a folder and see a context menu of available actions appear, as they do in the tree.

**Comment by shivamndave** [comment]
Just to clarify Victor, when having items in a folder, we need to be able to right-click those items and see the menu popup. However, right now it already does pop up the context menu for the tree on the left and in the grid view.

**Comment by VWoeltjen** [comment]
Oh, I see that it does! Looks like this got fixed in the context of another issue that was merged today; I'll mark this resolved.
